### ISSUE TITLE
Grype debug image no longer contains busybox

### ISSUE THREAD

**Issue by Uvedale** [anchore/grype#1010]
**What happened**: 
Trying to run busybox commands results in:

```
exec: "busybox": executable file not found in $PATH: unknown.
```

This is the same for v0.53.0

**What you expected to happen**: Busybox commands to work

**How to reproduce it (as minimally and precisely as possible)**: 
```docker run --rm -it --entrypoint busybox anchore/grype:v0.53.1-debug```
```docker run --rm -it --entrypoint busybox anchore/grype:v0.53.0-debug```

**Anything else we need to know?**:

It works in v0.52.0: ```docker run --rm -it --entrypoint busybox anchore/grype:v0.52.0-debug```

[This commit](https://github.com/anchore/grype/commit/3e0af433839eccef6fba4dc851b449b871af62ac) appears to have changed the base image to a non-debug distroless image. The debug distroless image is used in the main Dockerfile so perhaps they were switched by mistake.

**Environment**:
- Output of `grype version`: N/A
- OS (e.g: `cat /etc/os-release` or similar): N/A

**Comment by kzantow** [comment]
Good catch @Uvedale! PR opened to fix this 👍
