### ISSUE TITLE
grype scan by sbom file is generated by syft different with scanning directly container

### ISSUE THREAD

**Issue by waovu** [anchore/grype#1057]
grype scan by sbom file is generated by syft different with scanning directly container

grype scan sbom file and directly ccontainer should be same

<img width="1197" alt="Screen Shot 2023-01-11 at 2 11 28 PM" src="https://user-images.githubusercontent.com/27660379/211740990-5510bb61-f0e0-4113-a48d-e5a614ba4447.png">

**Environment**:
- `grype version`: 0.55.0
- syft version : 0.65.0
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by kzantow** [comment]
I suspect we're losing the _file overlap_ relationships in CycloneDX format.

As a workaround, you could use a Syft format SBOM (e.g. using `syft -o json`), and it should produce the same result as the direct scan.

**Comment by waovu** [comment]
> @katgurdak  yeap, If scan with json output, result will be same. but with cycloneDx format, it's difference
