### ISSUE TITLE
Support for `application/vnd.oci.image.index.v1+json` manifests in root OCI layout

### ISSUE THREAD

**Issue by saisatishkarra** [anchore/grype#1120]
**What would you like to be added**:
Refer: https://github.com/anchore/syft/issues/1545

**Why is this needed**:

**Additional context**:

**Comment by tgerla** [comment]
Hi @saisatishkarra, thanks for filing the corresponding issue for Syft--any changes will probably go there, so we'll close this one and continue discussion in the Syft issue.
