### ISSUE TITLE
Capturing Scan Results to a File (Proposed to add "--file" )

### ISSUE THREAD

**Issue by gh-greg** [anchore/grype#1146]
**What would you like to be added**:
Capturing **Scan Results to a File** (Proposed to add "**--file**" )

**Why is this needed**:
(a) I believe there is **currently no CLI option**,  (or even a "grype_config.yaml" file option ) ,  to directly tell the Grype runtime to **write** Grype Scan Results, to a **File**.
(b) Let me describe a "**Write Output File**" Use Case, that may benefit the entire community.
(c) Please see my section "**Competitor's Examples**" , below.
**TODAY**:
```
-o String
--output String
  Report output formatter, formats=[json table cyclonedx cyclonedx-json sarif template]
  Deprecated formats=[embedded-cyclonedx-vex-json embedded-cyclonedx-vex-xml]
```
**PROPOSED**: Add this new/complimentary option:
```
--file FileName
  Report output is written to the file specified
```

Currently: The only 2 ways to Capture Scan Results from Grype are:
(1) Shell redirection:
```
grype -o table busybox:1.21-ubuntu > grype_output_table.txt
grype -o json  busybox:1.21-ubuntu > grype_output_json.json
```
(2) Invoking from within some Programming Language:
```
grype_scan_results_string = run_wrapper( command: 'grype', args: [ docker_image.to_s, '-o', 'table' ])
grype_scan_results_string_processing( results_string: grype_scan_results_string  )
```
(3) PROPOSED:
```
grype -o json                         --file grype_output_json.json    busybox:1.21-ubuntu
grype -o table                        --file grype_output_table.txt    busybox:1.21-ubuntu
grype -o template -t my_template.tmpl --file grype_output_template.csv busybox:1.21-ubuntu
```
**MOTIVATION**:
Regarding (1): There are times when "Shell redirection" is either unavailable or considered inelegant.
Regarding (2): There are times when capturing Scan Result output as a Programming String, may eventually result in that String, being written out as a File anyway.
Regarding (3): The tool Grype mostly **exists**, to **write** "Scan Output".
The addition of "**--file**   scan_output" , would round out the most common scanning options, needed by Users.

**Additional context**:

**Competitor's Examples**:
**Prisma Cloud**: "**--output-file** FILENAME -- "  ## Write the results of the scan to a file in JSON format.
**SonarQube**: "sonar.scanner.metadataFilePath"  // Set the location where the scanner **writes** , **the report-task.txt** file.
**Fortify**:
```
sourceanalyzer -Dcom.fortify.sca.ProjectRoot=/local/proj/9999
-logfile /local/ssap/proj/9999/working/sca.log
-f  '/local/proj/output_file.fpr'

ReportGenerator -format pdf
-source '/local/proj/output_file.fpr'
-f  '/local/proj/output_file.pdf'
```
______
(KeithZ commented in Slack):
This is definitely something that would be good to add 
-- I would note for consistency with **Syft**, we might want to 
name this option just "**--file**" . 
But otherwise very much :+1: from me!
______

**Comment by kzantow** [comment]
Sorry, for some reason I missed this when I looked originally, but there already is a `--file` option that does what you'd like, so I think we can safely close this issue. Reach out if it doesn't work for you!

**Comment by gh-greg** [comment]
Thanks KeithZ.  For some reason ?
This output below, obscured this important "--file" flag, to my eyes at least.
```
 > grype --help | grep -i -C3  '\--file'
      --distro string         distro to match against in the format: <distro>:<version>
      --exclude stringArray   exclude paths from being scanned using a glob expression
  -f, --fail-on string        set the return code to 1 if a vulnerability is found with a severity >= the given severity, options=[negligible low medium high critical]
      --file string           file to write the report output to (default is STDOUT)
  -h, --help                  help for grype
      --only-fixed            ignore matches for vulnerabilities that are not fixed
      --only-notfixed         ignore matches for vulnerabilities that are fixed
```

**Comment by kzantow** [comment]
@gh-greg yeah, it did the same when you asked about it and I looked, too! I think I visually lumped it in with the `-f` somehow
