### ISSUE TITLE
failed to load vulnerability db: unable to get namespaces from store: database disk image is malformed

### ISSUE THREAD

**Issue by LOLCATATONIA** [anchore/grype#1150]
Grype DIRECTORY
results in "failed to load vulnerability db: unable to get namespaces from store: database disk image is malformed"

**grype version**
grype version
Application:          grype
Version:              0.57.1
Syft Version:         v0.72.0
BuildDate:            2023-02-16T20:09:55Z
GitCommit:            50a5c3324736d324dda334cd35ce9871db57efd2
GitDescription:       v0.57.1
Platform:             linux/amd64
GoVersion:            go1.19.5
Compiler:             gc
Supported DB Schema:  5

**cat /etc/os-release**
PRETTY_NAME="SparkyLinux 6.6 (Po-Tolo)"
NAME="SparkyLinux"
VERSION_ID="6.6"
VERSION="6.6 (Po-Tolo)"
ID=sparky
ID_LIKE=debian
HOME_URL="https://sparkylinux.org/"
SUPPORT_URL="https://sparkylinux.org/forum/"
BUG_REPORT_URL="https://sourceforge.net/p/sparkylinux/tickets"

**Comment by tgerla** [comment]
Hi there, can you try running:

grype db status

And:

grype db update

And send us the results? We'll be happy to take a look. Thanks.

**Comment by LOLCATATONIA** [comment]
The problem seems to have somehow resolved itself and I am not currently able to replicate it.

**Comment by tgerla** [comment]
OK, thank you for the update and please let us know if you have any more trouble!

**Comment by prbakhsh** [comment]
I had same issue. After delete db and update again my issue solved.
1- grype db delete
2- grype db update
