### ISSUE TITLE
Compilation error with github.com/anchore/sqlite v1.4.6-0.20220607210448-bcc6ee5c4963

### ISSUE THREAD

**Issue by Amar-Babu** [anchore/grype#1154]
**What happened**:
While upgrading go module import from github.com/anchore/grype v0.54.0 to v0.58 started noticing go compilation errors 
with github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go

**What you expected to happen**:
Expecting the go compilation to be successful and the unit tests to succeed.

**How to reproduce it (as minimally and precisely as possible)**:
clone the latest version of grype 
`git clone https://github.com/anchore/grype.git`
`cd grype`
`go get -u github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963`
`go mod tidy`
(Its the same version as what is mentioned in the go.mod file)
Also noticed that the tag v.1.4.6 for sqlite is missing in its [git repository](https://github.com/anchore/sqlite)
Optional -> `git diff go.mod` You will notice that few other transitive libs are upgraded

> diff --git a/go.mod b/go.mod
> index 4d685b0..c332b51 100644
> --- a/go.mod
> +++ b/go.mod
> @@ -47,7 +47,7 @@ require (
>  	github.com/x-cray/logrus-prefixed-formatter v0.5.2
>  	golang.org/x/term v0.5.0
>  	gopkg.in/yaml.v2 v2.4.0
> -	gorm.io/gorm v1.23.5
> +	gorm.io/gorm v1.24.6
>  )
>  
>  require (
> @@ -94,7 +94,7 @@ require (
>  	github.com/golang/snappy v0.0.4 // indirect
>  	github.com/google/go-containerregistry v0.13.0 // indirect
>  	github.com/google/martian/v3 v3.3.2 // indirect
> -	github.com/google/pprof v0.0.0-20211214055906-6f57359322fd // indirect
> +	github.com/google/pprof v0.0.0-20221118152302-e6195bd50e26 // indirect
>  	github.com/googleapis/enterprise-certificate-proxy v0.2.1 // indirect
>  	github.com/googleapis/gax-go/v2 v2.7.0 // indirect
>  	github.com/hashicorp/errwrap v1.1.0 // indirect
> @@ -105,7 +105,7 @@ require (
>  	github.com/inconshreveable/mousetrap v1.0.1 // indirect
>  	github.com/jinzhu/copier v0.3.5 // indirect
>  	github.com/jinzhu/inflection v1.0.0 // indirect
> -	github.com/jinzhu/now v1.1.4 // indirect
> +	github.com/jinzhu/now v1.1.5 // indirect
>  	github.com/jmespath/go-jmespath v0.4.0 // indirect
>  	github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51 // indirect
>  	github.com/klauspost/compress v1.15.11 // indirect
> @@ -114,7 +114,7 @@ require (
>  	github.com/logrusorgru/aurora v0.0.0-20200102142835-e9ef32dff381 // indirect
>  	github.com/magiconair/properties v1.8.7 // indirect
>  	github.com/mattn/go-colorable v0.1.13 // indirect
> -	github.com/mattn/go-isatty v0.0.16 // indirect
> +	github.com/mattn/go-isatty v0.0.17 // indirect
>  	github.com/mattn/go-runewidth v0.0.13 // indirect
>  	github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d // indirect
>  	github.com/microsoft/go-rustaudit v0.0.0-20220730194248-4b17361d90a5 // indirect
> @@ -131,7 +131,7 @@ require (
>  	github.com/pierrec/lz4/v4 v4.1.15 // indirect
>  	github.com/pkg/errors v0.9.1 // indirect
>  	github.com/pmezard/go-difflib v1.0.0 // indirect
> -	github.com/remyoudompheng/bigfft v0.0.0-20200410134404-eec4a21b6bb0 // indirect
> +	github.com/remyoudompheng/bigfft v0.0.0-20230129092748-24d4a6f8daec // indirect
>  	github.com/rivo/uniseg v0.2.0 // indirect
>  	github.com/sassoftware/go-rpmutils v0.2.0 // indirect
>  	github.com/shopspring/decimal v1.2.0 // indirect
> @@ -161,7 +161,7 @@ require (
>  	golang.org/x/sys v0.5.0 // indirect
>  	golang.org/x/text v0.7.0 // indirect
>  	golang.org/x/time v0.2.0 // indirect
> -	golang.org/x/tools v0.2.0 // indirect
> +	golang.org/x/tools v0.6.0 // indirect
>  	golang.org/x/xerrors v0.0.0-20220907171357-04be3eba64a2 // indirect
>  	google.golang.org/api v0.107.0 // indirect
>  	google.golang.org/appengine v1.6.7 // indirect
> @@ -170,14 +170,14 @@ require (
>  	google.golang.org/protobuf v1.28.1 // indirect
>  	gopkg.in/ini.v1 v1.67.0 // indirect
>  	gopkg.in/yaml.v3 v3.0.1 // indirect
> -	lukechampine.com/uint128 v1.1.1 // indirect
> -	modernc.org/cc/v3 v3.36.0 // indirect
> -	modernc.org/ccgo/v3 v3.16.6 // indirect
> -	modernc.org/libc v1.16.8 // indirect
> -	modernc.org/mathutil v1.4.1 // indirect
> -	modernc.org/memory v1.1.1 // indirect
> -	modernc.org/opt v0.1.1 // indirect
> -	modernc.org/sqlite v1.17.3 // indirect
> -	modernc.org/strutil v1.1.1 // indirect
> -	modernc.org/token v1.0.0 // indirect
> +	lukechampine.com/uint128 v1.2.0 // indirect
> +	modernc.org/cc/v3 v3.40.0 // indirect
> +	modernc.org/ccgo/v3 v3.16.13 // indirect
> +	modernc.org/libc v1.22.3 // indirect
> +	modernc.org/mathutil v1.5.0 // indirect
> +	modernc.org/memory v1.5.0 // indirect
> +	modernc.org/opt v0.1.3 // indirect
> +	modernc.org/sqlite v1.21.0 // indirect
> +	modernc.org/strutil v1.1.3 // indirect
> +	modernc.org/token v1.1.0 // indirect
>  )

## TO REPLICATE
Option 1 :-> Run `go test ./... -v`

> go test ./... -v
\# github.com/anchore/sqlite
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:101:22: invalid operation: limit.Limit > 0 (mismatched types *int and untyped int)
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:102:24: invalid operation: limit.Limit <= 0 (mismatched types *int and untyped int)
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:103:21: cannot use -1 (untyped int constant) as *int value in assignment
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:106:39: cannot use limit.Limit (variable of type *int) as int value in argument to strconv.Itoa

Option 2 -> Running lint fails `golangci-lint run -v ./...`

> INFO [config_reader] Config search paths: [./ /Users/amarbabu/Repositories/Public/grype /Users/amarbabu/Repositories/Public /Users/amarbabu/Repositories /Users/amarbabu /Users /]
INFO [config_reader] Used config file .golangci.yaml
INFO [lintersdb] Active 29 linters: [asciicheck bodyclose depguard dogsled dupl errcheck exportloopref funlen gocognit goconst gocritic gocyclo gofmt goprintffuncname gosec gosimple govet ineffassign misspell nakedret nolintlint revive staticcheck stylecheck typecheck unconvert unparam unused whitespace]
INFO [loader] Go packages loading at mode 575 (exports_file|files|imports|name|compiled_files|deps|types_sizes) took 1.3377655s
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 12.377583ms
INFO [linters_context/goanalysis] analyzers took 1m29.573905043s with top 10 stages: buildir: 37.121026915s, the_only_name: 7.29514112s, buildssa: 5.791285834s, fact_deprecated: 4.458926743s, ctrlflow: 4.315311753s, printf: 4.139454713s, fact_purity: 2.928021905s, nilness: 2.904462833s, typedness: 2.568806899s, SA5012: 2.447564422s
INFO [runner/max_same_issues] 21/24 issues with text "unnecessary trailing newline" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 8/11 issues with text "commentFormatting: put a space between `//` and comment text" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 3/6 issues with text "could not import github.com/anchore/sqlite (-: # github.com/anchore/sqlite\n../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:101:22: invalid operation: limit.Limit > 0 (mismatched types *int and untyped int)\n../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:102:24: invalid operation: limit.Limit <= 0 (mismatched types *int and untyped int)\n../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:103:21: cannot use -1 (untyped int constant) as *int value in assignment\n../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:106:39: cannot use limit.Limit (variable of type *int) as int value in argument to strconv.Itoa)" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 3/6 issues with text "unnecessary leading newline" were hidden, use --max-same-issues
INFO [runner] Issues before processing: 2030, after processing: 75
INFO [runner] Processors filtering stat (out/in): autogenerated_exclude: 2030/2030, identifier_marker: 2030/2030, max_per_file_from_linter: 110/110, max_same_issues: 75/110, severity-rules: 75/75, path_prettifier: 2030/2030, skip_dirs: 2030/2030, exclude: 2030/2030, diff: 110/110, source_code: 75/75, exclude-rules: 1211/2030, nolint: 1180/1211, path_shortener: 75/75, path_prefixer: 75/75, sort_results: 75/75, cgo: 2030/2030, filename_unadjuster: 2030/2030, skip_files: 2030/2030, uniq_by_line: 110/1180, max_from_linter: 75/75
INFO [runner] processing took 411.97775ms with stages: exclude-rules: 287.582667ms, identifier_marker: 78.965667ms, autogenerated_exclude: 21.908ms, nolint: 12.554375ms, path_prettifier: 6.558542ms, source_code: 3.373958ms, skip_dirs: 755.583µs, max_same_issues: 99µs, cgo: 81.084µs, uniq_by_line: 39.208µs, filename_unadjuster: 33.833µs, path_shortener: 13.125µs, max_from_linter: 8.292µs, max_per_file_from_linter: 3.333µs, diff: 209ns, severity-rules: 208ns, sort_results: 208ns, exclude: 208ns, skip_files: 167ns, path_prefixer: 83ns
INFO [runner] linters took 12.065926833s with stages: goanalysis_metalinter: 11.653872958s
grype/db/internal/gormadapter/open.go:9:2: could not import github.com/anchore/sqlite (-: # github.com/anchore/sqlite
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:101:22: invalid operation: limit.Limit > 0 (mismatched types *int and untyped int)
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:102:24: invalid operation: limit.Limit <= 0 (mismatched types *int and untyped int)
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:103:21: cannot use -1 (untyped int constant) as *int value in assignment
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:106:39: cannot use limit.Limit (variable of type *int) as int value in argument to strconv.Itoa) (typecheck)
	"github.com/anchore/sqlite"
	^
grype/db/v1/store/store.go:14:4: could not import github.com/anchore/sqlite (-: # github.com/anchore/sqlite
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:101:22: invalid operation: limit.Limit > 0 (mismatched types *int and untyped int)
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:102:24: invalid operation: limit.Limit <= 0 (mismatched types *int and untyped int)
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:103:21: cannot use -1 (untyped int constant) as *int value in assignment
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:106:39: cannot use limit.Limit (variable of type *int) as int value in argument to strconv.Itoa) (typecheck)
	_ "github.com/anchore/sqlite" // provide the sqlite dialect to gorm via import
	  ^
grype/db/v2/store/store.go:14:4: could not import github.com/anchore/sqlite (-: # github.com/anchore/sqlite
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:101:22: invalid operation: limit.Limit > 0 (mismatched types *int and untyped int)
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:102:24: invalid operation: limit.Limit <= 0 (mismatched types *int and untyped int)
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:103:21: cannot use -1 (untyped int constant) as *int value in assignment
../../../go/pkg/mod/github.com/anchore/sqlite@v1.4.6-0.20220607210448-bcc6ee5c4963/sqlite.go:106:39: cannot use limit.Limit (variable of type *int) as int value in argument to strconv.Itoa) (typecheck)

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`: any version 
- OS (e.g: `cat /etc/os-release` or similar): mac 13.2 (22D49)

**Comment by tgerla** [comment]
Hi @Amar-Babu, thanks for the report! We looked into this and it looks like the "-u" option to "go get" is upgrading more dependencies than you need, including gorm which appears to be causing your problem. For now we need to stay on gorm 1.23. If you try again from a fresh Grype checkout, and run "go get" without -u, do you have any better results?

This is the problem:

go: upgraded gorm.io/gorm v1.23.10 => v1.25.0

**Comment by Amar-Babu** [comment]
Hi @tgerla, Thanks for investigating this issue and sharing your suggestions.
I can confirm that if i use `go get gorm.io/gorm@v1.23.10` then we can overcome the compilation issue. 

As you have mentioned the issue is with the usage of `go get` with `-u` flag which on further reading helped me realize is not the best fit when we import 3rd party libraries which is very likely to have strong dependencies with certain library version (like gorm.io.gorm v1.23.10 in the case of grype) 

Going forward I shall upgrade to latest version of grype using 
`go get github.com/anchore/grype@v0.61.1`

**Comment by tgerla** [comment]
Great, thank you for the update!
