### ISSUE TITLE
Grype|Include Timestamp and Image Name to Reports

### ISSUE THREAD

**Issue by mike-19** [anchore/grype#1170]
**What would you like to be added**:

Include data like the timestamp on when grype scan was run and also the image name to the report information. 

**Why is this needed**:
This is required to provide structural data for visualization as well evidence for the scan report is associated with the particular image and was executed on a particular date (sort it to the latest) - Evidence needs to be provided for perusals

**Comment by spiffcs** [comment]
👋 Thanks for the issue @mike-19 - when you run `grype -o json <IMAGE>` I think you can see the image name under `source.target.userInput`

If the user input is something different then `source.target.tags` might also give you what you need for the image report.

As for timestamp I think that's an easy add.

Are there other formats you're looking for this update in? Were you specifically referencing a report/format type when filing the issue?

**Comment by mike-19** [comment]
@spiffcs  Thanks for the follow-up; based on your comments, I went through the JSON, and I was able to get the image name 
`timestamp` of when the scan was run with timezone would be helpful 
I am not looking for any other formats

**Comment by Shanedell** [comment]
Should this be closed? Looked like it was added in https://github.com/anchore/grype/commit/04c0bc1bcde0b28600acd720447243307aca93b0

**Comment by kzantow** [comment]
@Shanedell good catch -- looks like this was completed with #1249
