### ISSUE TITLE
Don't match new insert manually vulnerabilities

### ISSUE THREAD

**Issue by Dungeon1** [anchore/grype#1171]
**What happened**:
I try insert in vulnerability.db new row. Vulnerability.db downloaded from "grype db update". After this i try start scanning rpm package with version older than in vulnerability.db, but grype dont found vulnerabilities. This package unique and not contained in vulnerability.db

**What you expected to happen**:
Insert custom vulnerabilities.
**How to reproduce it (as minimally and precisely as possible)**:
Add manually row from attached screenshot. Download rpm https://git.altlinux.org/tasks/270602/build/200/x86_64/srpm/gnutls30-3.6.15-alt2.src.rpm to scanning 
**Anything else we need to know?**:

**Environment**:
- Output of `grype version `:latest:master
<img width="963" alt="Снимок экрана 2023-03-10 в 14 21 09" src="https://user-images.githubusercontent.com/36472686/224304844-357e819d-f5c9-46be-a90d-102e986c5e7a.png">
<img width="1532" alt="Снимок экрана 2023-03-10 в 14 21 55" src="https://user-images.githubusercontent.com/36472686/224304853-2e587041-b685-4e84-bb1d-c540672bfaeb.png">

- OS (e.g: `cat /etc/os-release` or similar): Debian

**Comment by spiffcs** [comment]
I also added enhancement to this so that we can explore what it might look like from the CLI updating/modifying the DB and if we want to explore that path at all.

**Comment by Dungeon1** [comment]
Maybe anyone know how can manually insert vulners in db? Add row in vulnerability and vulnerability_metadata tables. When start scan select distro(--distro altlinux:8.4) how in row(Column namespace; value: altlinux:distro:altlinux:8.4)

**Comment by Dungeon1** [comment]
@tgerla Hi. Altlinux vuln db in developing, but they have https://packages.altlinux.org/ru/p10/security/ for each branch. I wrote script parser, where collect data about fix packages from site and build sql query for sqlite db grype. Thanks for information!

**Comment by kzantow** [comment]
Hi @Dungeon1, as @tgerla mentioned, we have open source Grype DB and Vunnel which are responsible for processing vulnerability data sources and building the Grype database. This seems like a prime candidate to implement an Altlinux Vunnel provider to get the information input into the Grype db, would you like to contribute to an effort to support Altlinux?
