### ISSUE TITLE
:grey_question: Parsing dpkg status: extracting key-value from line:  usr/lib/os-release err: cannot parse field

### ISSUE THREAD

**Issue by adriens** [anchore/grype#1195]
# :grey_question:  What happened

When trying to use grype on a contenirez env,  I got this error message

```
WARN parsing dpkg status: extracting key-value from line:  usr/lib/os-release
err: cannot parse field from line usr/lib/os-release' form-lib=syft
```
... then it geneated me an empty json

# :dart:  What you expected to happen

I hoped to get a normal json

# :footprints:  Steps to reproduce

1. Download grype binary on Kaggle
2. `grype -o json optnc/colisnc-api > grype-jsons/colisnc-api.json`
3. Get the error message

**Anything else we need to know?**:
- Live Notebook : https://www.kaggle.com/code/adriensales/wip-grype-analysis

![image](https://user-images.githubusercontent.com/5235127/227809154-b0cd6df6-0b78-4393-bafc-a33bfda41bc2.png)

![image](https://user-images.githubusercontent.com/5235127/227809127-c5bd5d41-90cb-4789-b4d3-44f9a88d224d.png)

![image](https://user-images.githubusercontent.com/5235127/227809629-9ae7fc56-4d02-459c-9cf9-277780e9f49c.png)

**Comment by tgerla** [comment]
Hi @adriens, thanks for the report. I am having some trouble reproducing this problem. When I run, on my MacOS desktop, the following command:

grype -o json optnc/colisnc-api > tmp.json

...I get the expected json output and no warnings. This is with Grype 0.60.

It looks like the other images in the optnc namespace are correctly parsed, right? Is it just the optnc/colisnc-api image that is causing problems? What can you tell us about that image, and how it might be different from others that are analyzed successfully? Can you try it outside of the containerized environment? We will be happy to try to help.

**Comment by adriens** [comment]
Fxied by using recommanded install steps : 

```shell
curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
```

**Comment by adriens** [comment]
Thank you @tgerla for the feebdack, everything is fine while using the shell install vs. dry binary : 

![image](https://user-images.githubusercontent.com/5235127/230235008-7d6fe1f6-7ed3-4469-b5de-5556f3c87263.png)


I'll can have some fun now around grype and datascience :rocket:
