### ISSUE TITLE
Allow for access to private CAs securely

### ISSUE THREAD

**Issue by 5p2O5pe25ouT** [anchore/grype#1226]
Our registry uses certificate verification, insecure-skip-tls-verify is not allowed. How do I carry the certificate?

**Comment by tgerla** [comment]
Thanks for the pull requests, @5p2O5pe25ouT, I'm just linking these here for convenience:

https://github.com/anchore/stereoscope/pull/169
https://github.com/anchore/syft/pull/1734
https://github.com/anchore/grype/pull/1232

**Comment by 5p2O5pe25ouT** [comment]
> Thanks for the pull requests, @5p2O5pe25ouT, I'm just linking these here for convenience:
> 
> [anchore/stereoscope#169](https://github.com/anchore/stereoscope/pull/169) [anchore/syft#1734](https://github.com/anchore/syft/pull/1734) #1232

Thank you, if there is anything else that needs to be added, please contact me
