### ISSUE TITLE
Do a best effort on `setup.py` for Python projects

### ISSUE THREAD

**Issue by alfredodeza** [anchore/grype#126]
**What would you like to be added**: Python projects have `setup.py` that most analyzers/parsers out there fully ignore. This happens because the assignment of values to the dependency list can be dynamic, with variables, or with different formats. `grype` should attempt to identify versions in `setup.py` files that are pinned (using `==`). 

For example this is an extract from Pytest's `setup.py` file:

```python
requires = [
    'chardet>=3.0.2,<4',
    'idna>=2.5,<3',
    'urllib3>=1.21.1,<1.26,!=1.25.0,!=1.25.1',
    'certifi>=2017.4.17'

]
test_requirements = [
    'pytest-httpbin==0.0.7',
    'pytest-cov',
    'pytest-mock',
    'pytest-xdist',
    'PySocks>=1.5.6, !=1.5.7',
    'pytest>=3'
]
```

In this case, `grype` should be able to _only_ pick up: `'pytest-httpbin==0.0.7'`

**Why is this needed**: Enhances checks on Python projects that don't use a `requirements.txt` file.

**Comment by wagoodman** [comment]
Definitely want this feature! These details should be tracked under the syft issue to expand out the catalogers https://github.com/anchore/syft/issues/59 . This issue can track the work of amending the python matcher to include the new package type (or maybe use the same package) and adding tests.

**Comment by wagoodman** [comment]
Since this has been implemented in syft, and grype has incorporated at least that syft version, this is now supported in grype 🎉
