### ISSUE TITLE
Document command line flag for config file location

### ISSUE THREAD

**Issue by eslamkarim** [anchore/grype#1271]
**What would you like to be added**:
An extra custom place to search for `.grype.yaml` config file. it can be an environment variable for the path.

**Why is this needed**:
right now, the only places are static and in a ci/cd environment sometimes we want to make sure that the config file we specify is the one being used either it's in the shared directory or somewhere else maybe even a different config file for different steps (for a different ignore list of cve) etc

**Additional context**:
right now, the places grype searches for its configurations are. 
`
.grype.yaml 
.grype/config.yaml 
~/.grype.yaml 
<XDG_CONFIG_HOME>/grype/config.yaml
`

I am not sure if <XDG_CONFIG_HOME> is configurable or an env variable that we can change because if yes then that's exactly what we need.

**Comment by kzantow** [comment]
@eslamkarim you can use the `--config` / `-c` flag when running Grype to specify a config file. Does this not work for you for some reason?

**Comment by eslamkarim** [comment]
Oh, i didn't know that existed to be honest so that's perfect then.
on the config file section, it only mentioned where it was looking for the file but didn't mention there is a flag

**Comment by kzantow** [comment]
@eslamkarim yeah, I just noticed it's not mentioned in the docs -- I'll leave this issue open to get them updated. But you can see all the flags with `grype --help`

**Comment by eslamkarim** [comment]
thanks a lot for the help.
