### ISSUE TITLE
Feature Request: Grype server mode for caching downloaded DB vulnerability info

### ISSUE THREAD

**Issue by HariSekhon** [anchore/grype#1293]
**What would you like to be added**:

A Grype server mode equivalent to Trivy's server mode:

https://aquasecurity.github.io/trivy/v0.41/docs/references/modes/client-server/

**Why is this needed**:

I'm running code and container scanning in Jenkins on Kubernetes which spawns an ephemeral Jenkins agent per pipeline, resulting in repetitive minutes of download time wasted for every pipeline run that uses Grype.

With Trivy, I implemented Trivy server on Kubernetes:

https://github.com/HariSekhon/Kubernetes-configs/tree/master/trivy/base

and this took my Trivy stage time down from 15 minutes to a few seconds because most of the time is lost downloading vulnerability DB info rather than scanning with these tools.

Trivy server gave fast local cached access to the downloaded vulnerabilities DBs persisting in the Trivy running in server mode on Kubernetes, which is used by each Trivy CLI referencing it for the DB info via the `--server` switch, improving the speed of my pipelines using Trivy dramatically.

I would like to achieve something similar with Grype which is a performance bottleneck right now due to having to re-download the DB into every ephemeral Jenkins agent from scratch every single time for every single pipeline run.

**Comment by HariSekhon** [comment]
Looks like somebody has tried to do something similar here but without traction:

https://github.com/openclarity/grype-server

**Comment by tgerla** [comment]
Hi @HariSekhon, at this time we don't have any plans to implement a server mode like you describe. We might suggest using something like https://github.com/j3t/jenkins-pipeline-cache-plugin or something that might be more appropriate for your specific build pipeline.

In any case, the vulnerability database is updated every 24 hours so you will want to download it at least that often. Hope this helps and let us know if you have any other questions!

**Comment by HariSekhon** [comment]
Downloading the vulnerability DB every 24 hours is fine as long as it happens asynchronously from the build + deploy pipelines which scan the code or docker images in seconds by using the cached DB so as not to impact the pipeline timings.

For this reason most of the team insisted on stripping Grype out of pipelines.
