### ISSUE TITLE
match on most specific CPEs first

### ISSUE THREAD

**Issue by alfredodeza** [anchore/grype#140]
**What happened**: Similar to issue #94, but enhances what was proposed there with additions to handle the most specific CPEs before others.

**What you expected to happen**: We should be trying to match the most specific CPEs first (that is, try the CPEs with the fewest ANY wildcards).

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- grype version (use `grype version -v`):
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by wagoodman** [comment]
This has been implemented in syft (this logic used to reside in grype): https://github.com/anchore/syft/blob/ff828fbac211e1d9e993c309461bd9e0636fc2ec/syft/pkg/cataloger/cpe_specificity.go
