### ISSUE TITLE
ui: `New version` information should always be printed at top

### ISSUE THREAD

**Issue by Dentrax** [anchore/grype#1407]
```bash
grype foo/bar
 ✔ Vulnerability DB        [updated]
New version of grype is available: 0.64.2 (currently running: 0.64.0)
 ✔ Parsed image
 ✔ Cataloged packages      [X packages]
 ✔ Scanning image...
```

I noticed `New version` log printed out during scanning. I'd be better to log out at the first and then start the scanning process.

**Comment by wagoodman** [comment]
This has been fixed with https://github.com/anchore/grype/pull/1385 and https://github.com/anchore/grype/pull/1445 (and already released 🎉 )
