### ISSUE TITLE
Grype hangs forever if gets interrupted during work (in rare cases)

### ISSUE THREAD

**Issue by Dentrax** [anchore/grype#1427]
**What happened**:

```
grype registry.k8s.io/dns/k8s-dns-node-cache:1.22.22
```

<img width="1756" alt="Screenshot 2023-08-10 at 22 00 47" src="https://github.com/anchore/grype/assets/16493751/81a31058-444d-4099-acf9-c29c817d6055">

**What you expected to happen**:

It should terminated if `SIGTERM` or `SIGQUIT` received during runtime.

**How to reproduce it (as minimally and precisely as possible)**:

🤷‍♂️ 

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:
```
Application:          grype
Version:              0.65.1
Syft Version:         v0.86.1
BuildDate:            2023-08-04T13:02:31Z
GitCommit:            078a6c5e9e6e9e6e1037da6dcf953623e7d38500
GitDescription:       v0.65.1
Platform:             darwin/arm64
GoVersion:            go1.19.11
Compiler:             gc
Supported DB Schema:  5
```
- OS (e.g: `cat /etc/os-release` or similar): `macOS 13.4.1`

cc @luhring

**Comment by wagoodman** [comment]
@kzantow mind checking if the port to clio resolves this?

**Comment by wagoodman** [comment]
dev note: this is explicitly when you are mid run (and is not expected to fail/hang) and when cataloging starts (or db download starts) you interrupt with ctrl-c, then you can get to this condition. You should be able to hit this when immediately hitting ctrl-c on startup.
