### ISSUE TITLE
I would like a legacy.Execute() without the os.Exit(1)

### ISSUE THREAD

**Issue by harve106** [anchore/grype#1435]
**What would you like to be added**:
These lines of code in github.com\anchore\grype@v0.65.1\cmd\grype\cli\legacy\cmd.go
```
func ExecuteNoExit() {
	if err := rootCmd.Execute(); err != nil {
		_ = stderrPrintLnf(err.Error())
	}
}
```
**Why is this needed**:
I need it in order to use this function as I would the command line app because it's way easier to screen scrape than to go through APIs for simple usage

**Comment by harve106** [comment]
I have a PR that implements the functionality I would like with your old method of calling Execute(), https://github.com/anchore/grype/pull/1436

**Comment by kzantow** [comment]
Hi @harve106, the aforementioned PR has been merged and you can run grype CLI using this code:
```go
package main

import (
	"fmt"
	"github.com/anchore/clio"
	"github.com/anchore/grype/cmd/grype/cli"
)

func executeGrype() {
	cmd := cli.Command(clio.Identification{
		Name:    "my-app-name",
		Version: "[not provided]",
	})
	_ = cmd.Execute()
}

func main() {
	executeGrype()
	fmt.Println("post-execute")
}
```
It does not call `os.Exit`.

However, I think it would be better to use Grype as a library. I took a stab at this and ended up running into a few issues, but would suggest we look at how to improve the experience of using Grype as a library. Could you expand on your use case at all?

**Comment by tgerla** [comment]
Hey @harve106, we'll go ahead and close this issue out but please feel free to let us know if you need any more help here. Thanks!
