### ISSUE TITLE
Jar file get vulnerability reported when no suffix is added after the product name.  

### ISSUE THREAD

**Issue by sekveaja** [anchore/grype#1443]
**What happened**:

We have here dom4j  version 2.1.3 is fixing this vulnerability GHSA-hwj3-m3p6-hj38.

When grype scan on jar file named as "product + suffix".jar, it is not a problem i.e dom4j-2.1.3.jar.
As soon as, we rename to  dom4j.jar, without suffix,  Grype report vulnerabilty.

**What you expected to happen**:
Scanning on the same jar file with or without suffix should give the same result. 

**How to reproduce it (as minimally and precisely as possible)**:

1)  wget https://repo1.maven.org/maven2/org/dom4j/dom4j/2.1.3/dom4j-2.1.3.jar
2) Test
$ grype ./dom4j-2.1.3.jar
 ✔ Vulnerability DB                [no update available]
 ✔ Indexed file system                                                                                             /tmp
 ✔ Cataloged packages              [1 packages]
 ✔ Scanned for vulnerabilities     [0 vulnerabilities]
   ├── 0 critical, 0 high, 0 medium, 0 low, 0 negligible
   └── 0 fixed
[0000]  WARN unable to access path="/tmp/systemd-private-363d1309eeb04fccbd61c53ec1208496-chronyd.service-6IVyii": open /

3) Now rename to dom4j,jar
    $ cp dom4j-2.1.3.jar dom4j.jar

4) Test
$ grype ./dom4j.jar
 ✔ Vulnerability DB                [no update available]
 ✔ Indexed file system                                                                                             /tmp
 ✔ Cataloged packages              [1 packages]
 ✔ Scanned for vulnerabilities     [2 vulnerabilities]
   ├── 1 critical, 1 high, 0 medium, 0 low, 0 negligible
   └── 0 fixed
[0000]  WARN unable to access path="/tmp/systemd-private-363d1309eeb04fccbd61c53ec1208496-chronyd.service-6IVyii": open /
NAME   INSTALLED  FIXED-IN  TYPE          VULNERABILITY        SEVERITY
dom4j                       java-archive  GHSA-hwj3-m3p6-hj38  Critical
dom4j                       java-archive  GHSA-6pcc-3rfx-4gpm  High

5) Other tests
   $ mv dom4j.jar dom4j-anything.jar                  ----> No vulnerability reported on dom4j-anything.jar
   $ mv dom4j-anything.jar dom4j-.jar                 ----> No vulnerability reported on dom4j-.jar
   $  mv dom4j_2.1.3.jar dom4j213.jar                   ----> No vulnerability reported on dom4j213.jar
   $  mv dom4j_2.1.3.jar dom4jtwoonethree.jar    ----> No vulnerability reported on dom4jtwoonethree.jar
**   $  mv dom4j_2.1.3.jar dom4j                              ----> No vulnerability reported on dom4j      ***
   
See  **  when .jar extension is omitted i.e  dom4j  there is no issue reported.
Sound like it is expecting some suffix after the product name that has extension .jar

     
                 

   

**Anything else we need to know?**:
$ grype version
Application:          grype
Version:              0.65.2
Syft Version:         v0.87.1
BuildDate:            2023-08-18T00:36:56Z
GitCommit:            51223cd0b1069c7c7bbc27af1deec3e96ad3e07d
GitDescription:       v0.65.2
Platform:             linux/amd64
GoVersion:            go1.20.1
Compiler:             gc
Supported DB Schema:  5

**Comment by tgerla** [comment]
I tried running Syft against both filenames:

Version included:
```
tgerla@Timothys-MacBook-Pro-2 grype-1443 % syft dom4j-2.1.3.jar
 ✔ Indexed file system                                                                                                                             /Users/tgerla/git/test/grype-1443
 ✔ Cataloged packages              [1 packages]
NAME   VERSION  TYPE
dom4j  2.1.3    java-archive
```

No version:

```
tgerla@Timothys-MacBook-Pro-2 grype-1443 % syft dom4j.jar
 ✔ Indexed file system                                                                                                                             /Users/tgerla/git/test/grype-1443
 ✔ Cataloged packages              [1 packages]
NAME   VERSION  TYPE
dom4j           java-archive
```

I think what's happening is that there is nothing inside the Jar file to indicate the package version. When we scan the jar file with the version, Grype knows that 2.1.3 has fixed the issue so no vulnerability is reported. But when there's no version available, we don't know if it's fixed or not, so the vulnerability is reported.

**Comment by tgerla** [comment]
We'll go ahead and close this issue but if you need any more help here, please let us know!
