### ISSUE TITLE
Add CycloneDX Schema Validation

### ISSUE THREAD

**Issue by wagoodman** [anchore/grype#148]
**What would you like to be added**: Similar to https://github.com/anchore/syft/pull/163, we should be testing the output of the grype CycloneDX report against a XML schema validator that includes the [vulnerability extension](https://github.com/CycloneDX/specification/blob/master/schema/ext/vulnerability-1.0.xsd).

**Why is this needed**: This is to ensure we do not release CycloneDX presenter changes that generate non-compliant XML without manual verification.

**Comment by alfredodeza** [comment]
Thanks for tracking this one
