### ISSUE TITLE
unable to use DockerTarball source: cannot process multiple docker manifests

### ISSUE THREAD

**Issue by Soopx** [anchore/grype#1491]
**What happened**:
when scanning a tarfile, I get:
failed to catalog: could not fetch image '/project/mydockerimages-1.tar': unable to use DockerTarball source: cannot process multiple docker manifests

**What you expected to happen**:
I expected it to scan the file as normal

**How to reproduce it (as minimally and precisely as possible)**:
I'm unsure - it's literally just this package it happens with, but I have no idea why it's happening.  There is only one manifest present.  I'm unfamiliar with Grype.

**Anything else we need to know?**:

So apparently it's using v1.3.0, and it's running on docker.  I don't think it's a problem with Grype, yet the package looks fine, so I don't know what else to do

**Environment**:
- Output of `grype version`:
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by tgerla** [comment]
Hi @Soopx, sorry for the long delay replying! Can you share a bit more about what you're doing here, the exact commands you're running, and the rest of the output from Grype? We also need to know the version of Grype you are using, so please include the output of "grype version". Thanks.

**Comment by tgerla** [comment]
Since we haven't heard back, we're going to close this issue but please feel free to re-open once you are able to provide the requested info. Thanks!
