### ISSUE TITLE
Consider adding caching and re-use of recent scans results

### ISSUE THREAD

**Issue by mirekphd** [anchore/grype#1500]
**What would you like to be added**:
The ability to re-use previous (but recent) scanning results if checksum hasn't changed (ideally per-layer, docker-style). 

**Why is this needed**:
The scanning of a single large image (like those for data science and ML purposes) can last for many minutes. Repeating this process for multiple parallel build pipelines (Jenkins) clogs up the I/O capacity even of the reasonably fast SSD drivers with RAID 10.

**Additional context**:
This caching idea is borrowed from the Docker builder, which is uses per-layer cache shared among all locally built images, which greatly speeds up builds. 

Ideally this new feature could be integrated with an automatically managed built-in scans database, just like the current vulnerabilities db. A maximum age on the scan results could be also imposed (just like on the vuln. db).

**Comment by tgerla** [comment]
I'm going to go ahead and close this issue because I don't think we are planning on implementing this kind of caching in Grype, but please do let us know if you need any help implementing another solution--happy to look into it.
