### ISSUE TITLE
Unable to start the grype

### ISSUE THREAD

**Issue by venkatn087** [anchore/grype#1529]
**What happened**:
Am trying to install grype in AWS ubnutu 22.04 by using the below command

ubuntu@ip-xxxxxxxx:~$ pwd
/home/ubuntu
ubuntu@ip-xxxxxxx:~$ sudo curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
[info] checking github for the current release tag
[info] fetching release script for tag='v0.69.1'
[info] checking github for the current release tag
[info] using release tag='v0.69.1' version='0.69.1' os='linux' arch='amd64'
install: cannot create regular file '/usr/local/bin/grype': Permission denied
[error] failed to install grype
ubuntu@ip-172-31-46-28:~$

**What you expected to happen**:

It should install successfully
**How to reproduce it (as minimally and precisely as possible)**:
Create AWS Ubuntu 22.04 Medium tier instance
execute the below command 
sudo curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

i have referred the above url from https://github.com/anchore/grype

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:
- OS (e.g: `cat /etc/os-release` or similar):
- ubuntu@ip-xxxxxxxx:/usr/local/bin$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by SarveshRansubhe** [comment]
Was encountered with same issue, what i did was used i used this command on least access directory Eg: /media/{Drive} and then moved grype file to directory present in path Eg: /user/local/bin

**Comment by wagoodman** [comment]
This is common since /usr/local/bin is not writable by default. What @SarveshRansubhe is one option, but you can also use `sudo` on the second `sh` command:

```
curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin
```
