### ISSUE TITLE
CycloneDX based analysis failing

### ISSUE THREAD

**Issue by heubeck** [anchore/grype#1594]
**What happened**:
Grype 0.73.0 failes with 

```
# 0.73.0
grype sbom:vulnerable.json
1 error occurred:
        * failed to catalog: unable to decode sbom: sbom format not recognized
```

on CycloneDX 1.4 sboms, tested with [this](https://github.com/MediaMarktSaturn/technolinator/blob/main/src/test/resources/sbom/not-vulnerable.json) and [that](https://github.com/MediaMarktSaturn/technolinator/blob/main/src/test/resources/sbom/vulnerable.json), whereas Grype 0.72.0 could handle them:

```
# 0.72.0
grype sbom:vulnerable.json
 ✔ Vulnerability DB                [no update available]
 ✔ Scanned for vulnerabilities     [7 vulnerability matches]
   ├── by severity: 0 critical, 2 high, 5 medium, 0 low, 0 negligible
   └── by status:   7 fixed, 0 not-fixed, 0 ignored
[0000]  WARN some package(s) are missing CPEs. This may result in missing vulnerabilities. You may autogenerate these using: --add-cpes-if-none
NAME                 INSTALLED     FIXED-IN       TYPE          VULNERABILITY        SEVERITY
netty-codec-haproxy  4.1.85.Final  4.1.86.Final   java-archive  GHSA-fx2c-96vj-985v  Medium
netty-codec-http     4.1.85.Final  4.1.86.Final   java-archive  GHSA-hh82-3pmq-7frp  Medium
netty-codec-http2    4.1.85.Final  4.1.100.Final  java-archive  GHSA-xpw8-rcwv-8f8p  High
netty-handler        4.1.85.Final  4.1.94.Final   java-archive  GHSA-6mjq-h674-j845  Medium
quarkus-core         2.15.0.Final  2.16.8.Final   java-archive  GHSA-3fhx-3vvg-2j84  Medium
quarkus-vertx-http   2.15.0.Final  2.16.11.Final  java-archive  GHSA-4f4r-wgv2-jjvg  High
vertx-web            4.3.5         4.3.8          java-archive  GHSA-53jx-vvf9-4x38  Medium
A newer version of grype is available for download: 0.73.0 (installed version is 0.72.0)

grype sbom:not-vulnerable.json
 ✔ Vulnerability DB                [no update available]
 ✔ Scanned for vulnerabilities     [0 vulnerability matches]
   ├── by severity: 0 critical, 0 high, 0 medium, 0 low, 0 negligible
   └── by status:   0 fixed, 0 not-fixed, 0 ignored
[0000]  WARN some package(s) are missing CPEs. This may result in missing vulnerabilities. You may autogenerate these using: --add-cpes-if-none
No vulnerabilities found
```

**What you expected to happen**:
Grype 0.73.0 still able to handle CycloneDX (1.4+) sbom files.

**How to reproduce it (as minimally and precisely as possible)**:
run `grype sbom:cdx.json` with _cdx.json_ being a CycloneDX 1.4 formatted sbom like referenced sample files.

**Anything else we need to know?**:
You're doing a really great job, thanks!

**Environment**:
- Output of `grype version`: `grype 0.73.0`
- OS (e.g: `cat /etc/os-release` or similar): Tested on GitHub action runner ubuntu:latest and locally on Fedora 39

**Comment by willmurphyscode** [comment]
Thanks for reporting the issue!

This is because grype v0.73.0 depends on syft 0.95.0, which is affected by https://github.com/anchore/syft/issues/2299 (a bug where syft thinks CycloneDX JSON is document is invalid if it is missing the `$schema` field).

We plan to release a fix to syft and grype today.
