### ISSUE TITLE
Add criteria to the "fail-on" CLI flag

### ISSUE THREAD

**Issue by EnguerrandDeclercq** [anchore/grype#1614]
**What would you like to be added**:

It would be great if the fail-on CLI flag accepted other criteria than the sole CVE severity, such as the CVE patchability. 

**Why is this needed**:

Some CVEs are deemed critical but do not have an official patch (or won't be fixed at all), which means we cannot do much about it. However, critical CVEs that can be fixed are a top-priority since corrective actions can be taken immediately. In a CI pipeline context, an error triggered by such a CVE would make the job fail and force developers to take action. In such a scenario, a patchable high CVE would raise an error while a wont-fix critical CVE would have Grype exit with a 0 return code.

**Additional context**:

**Comment by tgerla** [comment]
Hi @EnguerrandDeclercq, thank you for the suggestion. Grype does have a `--only-fixed` flag which can be used ignore vulnerabilities with no patch available. Have you tried the combination of `--fail-on` and `--only-fixed`? I believe that combination would satisfy your example scenario. If this doesn't do what you need, let us know and we can discuss. Thanks!

**Comment by EnguerrandDeclercq** [comment]
Hello @tgerla, thanks for your response. This flag indeed outputs all CVEs without an official patch. However, I think that an option only discarding `wont-fix` CVEs would be a great feature. Sorry for not being crystal clear formulating my request :smile:

**Comment by tgerla** [comment]
We'll go ahead and close this issue since we haven't heard back, but feel free to re-open or open a new one if you need more help. Thanks!
