### ISSUE TITLE
Parameter `quiet` is ignored in configuration file

### ISSUE THREAD

**Issue by plavy** [anchore/grype#1645]
**What happened**: Setting `quiet: true` in YAML config file produces no effect, even though this parameter is mentioned in README. Same applies to `GRYPE_QUIET` env variable.

**What you expected to happen**: `quiet` from YAML file and `GRYPE_QUIET` form env should be taken into account.

**How to reproduce it (as minimally and precisely as possible)**: Set `quiet: true` in `.grype.yaml`. There is no effect.

**Anything else we need to know?**: I've investigated the source code and found that there is no parameter for quiet in file `/cmd/grype/cli/options/grype.go`. I've also found PR https://github.com/anchore/grype/pull/1437 that introduced CLIO as the base for CLI, which delegated handling of quiet to CLIO, and, I believe, removed it from the Grype config.

**Environment**:
- Output of `grype version`: 0.73.5
- OS (e.g: `cat /etc/os-release` or similar): Ubuntu 22.04.3 LTS

**Comment by kzantow** [comment]
Thanks for the report @plavy! You are right, it looks like the documentation was not updated with the CLIO port.

If you run `grype --help`, it will currently show you all the configuration file options as well as the associated environment variable, e.g.:
```
 log:
    # suppress all logging output (env: GRYPE_LOG_QUIET)
    quiet: false
```
