### ISSUE TITLE
Scan multiple input SBOMs

### ISSUE THREAD

**Issue by Leyart** [anchore/grype#1654]
**What would you like to be added**:

Allow grype to analyse multiple SBOM file provided as input in a single scan

**Why is this needed**:

Currently, grype generates a report by taking as input at most one SBOM file. The SBOM may come from multiple sources, generating multiple different SBOM files and yet we would like a single vulnerability report to be generated

**Comment by wagoodman** [comment]
This is a duplicate of https://github.com/anchore/grype/issues/1259 , I'll close this in the meantime, but shout out if there is a difference/nuance I missed.
