### ISSUE TITLE
Ephemeral CI documentation / grype db update

### ISSUE THREAD

**Issue by ArieLevs** [anchore/grype#1711]
**What would you like to be added**:
Ephemeral CI documentation

**Why is this needed**:
Documentation/best practice

**Additional context**:
Hi,
Our experience thus far with Grype has been quite positive; its out-of-the-box functionality aligns well with our requirements. However, I have encountered a challenge specific to our ephemeral Kubernetes (k8s) pod-based CI environment. Given that each pipeline initiates an ephemeral, clean environment, I am seeking a solution to manage the Grype vulnerability database efficiently.

Upon local testing, I observed that executing db update results in a substantial `1.1 GB`(!) vulnerability database file. While this size is manageable for local setups, it presents a logistical concern when extrapolated to our CI workflows. The prospect of fetching this database for every CI run from the [remote location](https://toolbox-data.anchore.io) could potentially lead to significant bandwidth consumption, with estimates suggesting it could accumulate to hundreds of gigabytes daily.

Could you kindly advise on a best-practice solution for this scenario? Apart from setting up an NFS-like storage for the [cache-dir](https://github.com/anchore/grype#local-database-cache-directory) and implementing daily updates to the database, is it feasible to host the database within a container? Utilizing a containerized database setup would enable internal caching of the image, potentially circumventing the need for public internet data transfers.

Thanks

**Comment by tgerla** [comment]
Hi @ArieLevs, thanks for your feedback! I think a similar issue has been discussed previously, in this thread: https://github.com/anchore/grype/issues/837 -- and @kzantow suggests an example Dockerfile to create a Grype container with the database included: https://github.com/anchore/grype/issues/837#issuecomment-1666123722

Let us know if this helps, otherwise we can provide some more suggestions.

**Comment by ArieLevs** [comment]
Hi @tgerla yes thanks, 
I've seen that thread just though there was an out of the box solution.
While I understand the rationale behind the proposed approach, it is worth noting that adopting it would still necessitate querying the entire database twice daily in a non cached way, once for each architecture. 
However, this strategy would streamline the process by providing a singular image for utilization in continuous integration pipelines. In contrast, utilizing a non-debug image, such as `anchore/grype:v0.74.5`, which supports both arm64 and amd64 architectures, poses limitations as the debug variant `anchore/grype:v0.74.5-debug-arm64v8` is platform-specific. This could prove challenging for environments with dynamic cloud resources, where instances may intermittently operate on arm/amd architectures.

thanks, this solution will work!
marking as closed

**Comment by OnceUponALoop** [comment]
Commenting on a closed issue in case someone runs into it and needs an alternative.

We utilize the CI caching and the `grype` db environment variables to do this in our workflow. This allows us to get the grype db daily and have it cached for our various CI runs.
