### ISSUE TITLE
Add instructions for offline installation

### ISSUE THREAD

**Issue by kruttjr** [anchore/grype#1772]
Please add instructions for how to install Grype and Syft utilizing the ZIP file clone option and place in the Installation section of the README file.

**Comment by tgerla** [comment]
Hi @kruttjr, the instructions from https://github.com/anchore/grype/blob/main/DEVELOPING.md#native-development should be suitable for the ZIP file clone download. Let us know if you need any more help. Out of curiosity, why are you installing Grype this way? Thanks!

**Comment by tgerla** [comment]
We'll go ahead and close this issue but please let us know if you need anything else.
