### ISSUE TITLE
Documentation missing mention of sarif output format

### ISSUE THREAD

**Issue by Jiri-Stary** [anchore/grype#1778]
**What happened**:
https://github.com/anchore/grype?tab=readme-ov-file#output-formats
is missing mention of "sarif" output format

**What you expected to happen**:
it should be listed as an option

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by tgerla** [comment]
Hi @Jiri-Stary, good catch, we'll update the docs shortly. Thank you for the report!
