### ISSUE TITLE
Latest database cannot be  downloaded via grype  db update

### ISSUE THREAD

**Issue by ep4sh** [anchore/grype#1878]
**What happened**:
Latest database cannot be  downloaded

download speed downs to 8-10kb/s

```
root@runner-st5swxhye-project-74-concurrent-0-xcj3mez2:/builds/devops/grype-db# wget https://toolbox-data.anchore.io/grype/databases/vulnerability-db_v5_2024-05-23T01:30:08Z_1716439560.tar.gz
--2024-05-23 11:37:36--  https://toolbox-data.anchore.io/grype/databases/vulnerability-db_v5_2024-05-23T01:30:08Z_1716439560.tar.gz
Resolving toolbox-data.anchore.io (toolbox-data.anchore.io)... 188.114.98.224, 188.114.99.224, 2a06:98c1:3122:e000::, ...
Connecting to toolbox-data.anchore.io (toolbox-data.anchore.io)|188.114.98.224|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 164589721 (157M) [application/x-tar]
Saving to: 'vulnerability-db_v5_2024-05-23T01:30:08Z_1716439560.tar.gz'

  vulnerability-db_v5_2024-05-23T01:30:08Z_  57%[==================================================>                                      ]  90.51M  16.3KB/s    eta 10s 
```

**What you expected to happen**:
db is downloaded

**How to reproduce it (as minimally and precisely as possible)**:
grype  db update

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:
grype 0.77.4

- OS (e.g: `cat /etc/os-release` or similar):
debian

**Comment by willmurphyscode** [comment]
Hi @ep4sh,

Thanks for the report!

It looks like the `wget` command you posted started downloading the database. Did it time out? What went wrong with it?

I just ran `grype db update` as well as the `wget` command from your post, and both succeeded without error. Are you able to run these now? Is there anything else you can tell me about what was going wrong?

**Comment by ep4sh** [comment]
Hmm, yeah, it was worth to write it - and booooom! magic! it works!
it might be a temporary network issue
Thanks for your time @willmurphyscode and for helping!
