### ISSUE TITLE
Allowlist/Whitelist Progress

### ISSUE THREAD

**Issue by luoyimu1** [anchore/grype#191]
Dear Team,

Just wondering what the current progress of the allowlist/whitelist is as i can see it's mentioned in the "Future plans".

We consider this as a critical feature to us and we'd also like to make contributions to Grype if PRs are acceptable.

We're thinking of implementing it by looking for a specific local file which contains the specified vulnerabilities allowlist and filter out them in the vulnerability scan result. What do you think?

Hope to hear from you soon.

Cheers,

**Comment by hev** [comment]
Hi @luoyimu1 - this is on our mind as well. It didn't make our next up sprint plan but it's not far off either. 

PR's are always welcome, and the approach you described sounds pretty similar to what we have discussed.  That said the design will need to consider compatibility with commercial products as we see policy as an extension point for us and other vendors to add value so we will need consider carefully the scope of what we offer and the syntax used.  

I'd suggest we work through some of the design concepts here before jumping into a PR. You can also catch us on our [community slack](https://anchorecommunity.slack.com/archives/C0190NF9TSM) if you want to arrange something more real time.

**Comment by luoyimu1** [comment]
Hey @hev, thanks a lot for your reply:)
Just wondering how i could join in the community slack channel? My slack email address is rluo54321@gmail.com
Thanks,

**Comment by wagoodman** [comment]
@luoyimu1 there should be a "sign up" link in the top right of the page that @hev linked (which goes to https://anchorecommunity.slack.com/signup#/ ), from there you should be able to join the community slack!

**Comment by luoyimu1** [comment]
@wagoodman , @hev , sorry to trouble you guys again, but I always get an error saying "The email address must match one of the domains listed below. Please try another email." when trying to sign up with my gmail account and the instruction below also mentions that:
You can use any account with the domain:

    anchore.com
    nvidia.com
    cisco.com

Don’t have an email address from one of those domains?
Contact the workspace administrator at Anchore Community for an invitation.

So I assume I need an invite to join in the channel?

**Comment by hev** [comment]
@luoyimu1 checking with our ops team.

**Comment by Btodhunter** [comment]
@luoyimu1 try this link - https://anchore.com/slack

**Comment by luoyimu1** [comment]
Thanks @Btodhunter, it works!!
CC: @hev, @wagoodman

**Comment by aries1980** [comment]
Closing this ticket means this feature has been implemented?

**Comment by luoyimu1** [comment]
@aries1980, nah, this ticket is just an enquiry about the progress of whitelist/allowlist, not related to the actual feature implementation.
