### ISSUE TITLE
"failed to catalog" error when scanning Python apps

### ISSUE THREAD

**Issue by luoyimu1** [anchore/grype#200]
**What happened**:
"failed to catalog" error when scanning Python apps:
[0006] ERROR failed to catalog: 1 error occurred:
unable to catalog python package=/usr/local/lib/python3.9/site-packages/distlib-0.3.1.dist-info/METADATA: missing python package top_level.txt (package="/usr/local/lib/python3.9/site-packages/distlib-0.3.1.dist-info/METADATA")	

**What you expected to happen**:
I dunno if top_level.txt is required in Python eggs, or whether Grype thinks they are required, but they are not really required

**How to reproduce it (as minimally and precisely as possible)**:
Python app source code:
https://github.com/luoyimu1/hermitcrab
Grype cmd I ran: grype <image> --scope all-layers

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`: 0.1.0, 0.2.0
- OS (e.g: `cat /etc/os-release` or similar): Linux

**Comment by wagde-orca** [comment]
@wagoodman i believe this is the same issue you fixed in syft. Right?
when do you expect to have the fix integrated in grype?

**Comment by luhring** [comment]
Closing as duplicate to https://github.com/anchore/syft/issues/259 — please see that issue for details. Thanks!
