### ISSUE TITLE
no grype db was published since 17.8

### ISSUE THREAD

**Issue by TimBrown1611** [anchore/grype#2065]
**What happened**:
It seems no grype db was published since 17.8
just want to make sure it is expected behave.
**What you expected to happen**:
Usually every day a new DB is published
**How to reproduce it (as minimally and precisely as possible)**:
`grype db update`
`grype db status`

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`: 0.79.5
- OS (e.g: `cat /etc/os-release` or similar): mac

**Comment by kzantow** [comment]
Thanks for the report, we've published the latest database and enabled the daily publishing to the new hosting.
