### ISSUE TITLE
go-sqlite package is broken since upgrading to golang 1.23

### ISSUE THREAD

**Issue by tomersein** [anchore/grype#2116]
**What happened**:
I see integration tests fails since upgrading to 1.23.0 \ recently
seems to be related to this issue - https://github.com/glebarez/go-sqlite/issues/176
I am able to run grype, but i am not sure this issue impacts it in some scenarios.
example of failure - 
https://github.com/anchore/grype/actions/runs/10814011631
**What you expected to happen**:
integration tests to pass
**How to reproduce it (as minimally and precisely as possible)**:
run integration tests.

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by willmurphyscode** [comment]
I believe this was fixed by https://github.com/anchore/grype/blob/641982ff47fcb8d56b9555e5f0dad23afa7bc690/go.mod#L269.

Please let us know if you're still experiencing integration test failures.
