### ISSUE TITLE
Grype reports false postive on go-tuf package - confuses v2/go-tuf with go-tuf (non-v2)

### ISSUE THREAD

**Issue by mamccorm** [anchore/grype#2175]
**What happened**:
Grype looks to be falsely reporting that images are affected by GHSA-4f8r-qqr9-fq8j, by not considering there are two different packages with similar names. One is a 'v2' package with differnt versioning, the other is not.

**What you expected to happen**:

I'd expect grype to be aware, that GHSA-4f8r-qqr9-fq8j affects 'go-tuf/v2', and NOT report any related findings, when scanning packages that contain 'go-tuf' - i.e the non-v2 version:

- https://pkg.go.dev/github.com/theupdateframework/go-tuf
- https://pkg.go.dev/github.com/theupdateframework/go-tuf/v2

**How to reproduce it (as minimally and precisely as possible)**:

Scan any image that contains the non-v2 version of go-tuf dependency. Here is one such example:

```bash
grype cgr.dev/chainguard/zot:latest
...
...
NAME                                  INSTALLED  FIXED-IN  TYPE       VULNERABILITY        SEVERITY
github.com/theupdateframework/go-tuf  v0.7.0     2.0.1     go-module  GHSA-4f8r-qqr9-fq8j  High
```

We can see that its correctly detected 'github.com/theupdateframework/go-tuf' and its the v1 version, and v0.7.0 is installed. This lines up with the latest version available here: https://pkg.go.dev/github.com/theupdateframework/go-tuf

But we are incorrectly saying its fixed in v2.0.1, which is not the case, as GHSA-4f8r-qqr9-fq8j  relates to go-tuf/v2

**Comment by willmurphyscode** [comment]
Hi @mamccorm thanks for the report!

Grype seems to be correctly interpreting the data here:

https://github.com/advisories/GHSA-4f8r-qqr9-fq8j lists:

Affected packages: 
*  github.com/theupdateframework/go-tuf  < 2.0.1
* github.com/theupdateframework/go-tuf/v2 < 2.0.1

If you look at the advisory JSON, you can see that both the non `/v2` and the `/v2` package are listed as vulnerable: https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/10/GHSA-4f8r-qqr9-fq8j/GHSA-4f8r-qqr9-fq8j.json#L21-L60

Also, https://pkg.go.dev/vuln/GO-2024-3166, says:

* [github.com/theupdateframework/go-tuf](https://pkg.go.dev/github.com/theupdateframework/go-tuf)
    all versions, no known fixed
* [github.com/theupdateframework/go-tuf/v2](https://pkg.go.dev/github.com/theupdateframework/go-tuf/v2)
    before v2.0.1

Do you believe this data is incorrect? If so, you could submit a PR to the GitHub advisory database, and Grype will respect the fix.

Is there a reason Grype shouldn't suggest upgrading from non `v2` to `v2` if the data sources say everything before `2.0.1` is vulnerable?

**Comment by mamccorm** [comment]
Thanks for the prompt reply @willmurphyscode. I can see the logic in the above, could be an issue with the GH advisory DB?

The latest version of github.com/theupdateframework/go-tuf is v0.7.0, so could be mis-classified
