### ISSUE TITLE
Colorize severity in table output

### ISSUE THREAD

**Issue by sprt** [anchore/grype#225]
It would be nice to display each severity label in its own color in the table output. Trivy does that well and it makes visually parsing the output just a little bit faster, with just a quick glance. I'd suggest something like low = blue, medium = yellow, high = red, critical = bold red. Happy to contribute a PR if you think this sounds interesting!

**Comment by luhring** [comment]
Hey @sprt, this sounds cool! This is certainly something we're open to. Our main considerations are that the colors are **a)** helpful (like you mention) and **b)** easily readable, even on a variety of terminal configurations (e.g. some folks prefer dark backgrounds, some prefer light backgrounds, etc.).

As for colors themselves, I think we'll have to see how it looks in context, but I'm sure this won't be a hard problem. One idea is to be consistent with our [grype VS Code extension](https://github.com/anchore/grype-vscode), specifically the "vulnerability report" view (whose code is here: https://github.com/anchore/grype-vscode/blob/main/src/ui/react-components/FindingsList.tsx#L148-L162).

If you want to take a stab at this, that'd be very helpful! I'd be more than happy to serve as a resource and walk through how we've designed the output mechanism.

**Comment by freedom-isnotanarchy** [comment]
Regarding ((display each severity label in its own color in the table output.)) :
(1) Might this also involve, implementing some new `--no-color` flag   ?
(2) I would be in the audience, that fears that this enhancement, might get in the way of some/many use cases, that this "default table" output, be easy to display  and manipulate, as the simplest ASCII-7 characters.

**Comment by wagoodman** [comment]
The PR has been updated to respond to the `NO_COLOR` and `CLICOLOR_FORCE` environment variables https://github.com/anchore/grype/pull/1284#issuecomment-1785241750
