### ISSUE TITLE
Grype Docker Image

### ISSUE THREAD

**Issue by blang9238** [anchore/grype#227]
**What would you like to be added**:
A published Docker image to run Grype.

**Why is this needed**:
With a published Docker image it would simplify usage in most CI environments. Without a published Docker image Grype is installed every time it runs within a CI environment.

**Additional context**:

**Comment by sparrowt** [comment]
I found https://hub.docker.com/r/anchore/grype but no instructions on how to run it. Eventually figured out the following (in order for grype to access, from inside the container, an image I had built on host)
```
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock anchore/grype:latest MYIMAGE:MYTAG
```
Assuming this is the recommended way (though it's not problem free see #372) it might be worth adding to the README (I can do this at some point but don't have the chance right now)

**Comment by luhring** [comment]
@sparrowt Good callout — just opened an issue to track Docker Hub documentation: https://github.com/anchore/grype/issues/388
