### ISSUE TITLE
Failure scanning `odoo:latest`

### ISSUE THREAD

**Issue by found-it** [anchore/grype#229]
**What happened**:

`grype` failed to catalog when scanning `odoo:latest`
```shell
[0037] ERROR failed to catalog: 1 error occurred:
        * unable to catalog python package=/usr/lib/python3/dist-packages/passlib-1.7.1.egg-info/PKG-INFO: cannot parse field from line: 'crypt md5-crypt'
```
**What you expected to happen**:

Expected `grype` to be able to scan the image.

**How to reproduce it (as minimally and precisely as possible)**:

```shell
grype odoo:latest
```

**Anything else we need to know?**:

n/a

**Environment**:
- Output of `grype version`:
```
Application:          grype
Version:              0.6.1
BuildDate:            2020-12-08T19:19:38Z
GitCommit:            9128a8af61ede2446c15492b526922a0091e2828
GitTreeState:         clean
Platform:             darwin/amd64
GoVersion:            go1.14.12
Compiler:             gc
Supported DB Schema:  1
```
- OS (e.g: `cat /etc/os-release` or similar):
```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H114
```

**Comment by luhring** [comment]
Closing as duplicate to https://github.com/anchore/syft/issues/309
