### ISSUE TITLE
Create a tekton task for grype

### ISSUE THREAD

**Issue by luhring** [anchore/grype#232]
It'd be great to integrate with the [tekton](https://tekton.dev/) ecosystem as a _task_, so that people can easily use Grype in their tekton pipelines.

At the time of writing, there are only 3 tasks in the category of "security" in the [tekton catalog](https://hub-preview.tekton.dev/).

See here for details: https://github.com/tektoncd/catalog#tekton-catalog

**Comment by developer-guy** [comment]
I want to work on this issue, can you please assign it to me @luhring? :)

**Comment by developer-guy** [comment]
Hello folks, I've completed the Tekton Task for grype, and will continue with the syft tool:

feat: add grype tektoncd/catalog#895

**Comment by luhring** [comment]
@developer-guy Fantastic! Let us know when this gets through the review process and merged, and we'll close this issue. 🚀

**Comment by wagoodman** [comment]
This was merged quite a while ago 😄
