### ISSUE TITLE
Be clear about version and data staleness 

### ISSUE THREAD

**Issue by wagoodman** [anchore/grype#240]
This is capturing the output from an internal conversation.

1. Today we do not fail a scan if the DB is stale (hasn't been updated within some "acceptable" time period). It would be ideal to allow for a **configurable** option (that is on by default) which controls the exit code to always be 1 if the result was made with a stale DB.
2. We should have a way to notify users of DB staleness warnings and other useful messages.
3. ~Question: Should we allow for downloading OLD DBs where the schemas are deprecated? Should this show a warning?~ (we haven't implemented a deprecation mechanism yet)
4. Should the application version banner show the existing version compared with the new version available? That may help with illustrating the need to update versions to users.

**Comment by jonasagx** [comment]
I can look into this.
