### ISSUE TITLE
allow development installations via install.sh

### ISSUE THREAD

**Issue by alfredodeza** [anchore/grype#253]
`install.sh` currently supports released versions of `grype` to be installed. Integrations like `scan-action` may want to test against unreleased versions of `grype` that are currently not possible to install with `install.sh`.

**Comment by alfredodeza** [comment]
This is now crucial to be able to produce newer database schemas that are using the un-released version of grype

**Comment by wagoodman** [comment]
We really want to encourage folks to install released versions of grype/syft when using install.sh. Installing a development version requires a build toolchain which is outside of the capabilities of install.sh (which tries to be compliant to unix standards).
