### ISSUE TITLE
Ability to pull image directly from a registry (without the Docker daemon)

### ISSUE THREAD

**Issue by luhring** [anchore/grype#264]
It would be advantageous if Grype could pull images directly from a container registry, in addition to its existing capabilities (relying on the Docker daemon or finding data locally).

Advantages of this method:

1. Grype can run within a container image and fetch container images without the user needing to expose the Docker daemon to the running container.
2. This can reduce wait times for users since the image would need to be pulled from the registry to the local system, rather than have an additional required step after the pull (i.e. retrieving the image from the Docker daemon). This improvement would be especially noticeable for larger images.

Open questions for consideration:

1. How will Grype handle authentication?
2. How will Grype handle private/custom CAs for registry access?
3. How will we decide when Grype will use this method of pulling an image vs. relying on the Docker daemon?
4. Should we consider any kind of local caching for images pulled directly from a registry?

**Comment by wagoodman** [comment]
Response to open questions:
1. This will need to be added to the application configuration (supporting username/password or by token)
2. This support will not be added, but is a possible addition by providing a custom `http.Transport` to the underlying gcrlib's `remote.Get` via the `remote.WithTransport` option (with the tls.Config adjusted properly)
3. Add an explicit `oci-registry` and `registry` schemes, falling back to the registry as a default only if docker is not reachable.
4. This seems outside of the scope
