### ISSUE TITLE
grype doesn't work with Go 1.14

### ISSUE THREAD

**Issue by alfredodeza** [anchore/grype#279]
**What happened**: Tried using grype with Go 1.14 which lead to errors:

```
Error: ../../../../go/pkg/mod/github.com/anchore/syft@v0.14.1-0.20210405182557-7a10cbae0c41/syft/file/digest_cataloger.go:90:38: hash.String undefined (type crypto.Hash has no field or method String)
Error: ../../../../go/pkg/mod/github.com/anchore/syft@v0.14.1-0.20210405182557-7a10cbae0c41/syft/file/secrets_search_by_line_strategy.go:99:18: pattern.SubexpIndex undefined (type *regexp.Regexp has no field or method SubexpIndex)
Error: Process completed with exit code 2.
```

**What you expected to happen**: At the very least, something in the documentation that mentions what are the Go versions that are supported. Ideally (unsure if this is possible) something that prevents usage in unsupported Go versions, or that produces a better error

**How to reproduce it (as minimally and precisely as possible)**: Run grype with Go 1.14

**Comment by luhring** [comment]
We should document the required steps for when we want to update the target Go version for the project. There are a few steps we need to include (updating CI, updating `go.mod`, updating documentation, etc.), and it's easy to miss a few steps.

One possibility is to have an issue template that lists the required tasks.

**Comment by luhring** [comment]
It could also be helpful to signal the Go version at the top of our README.md with a badge. This badge automatically displays the `go.mod` cited Go version:

`[![GitHub go.mod Go version](https://img.shields.io/github/go-mod/go-version/anchore/grype.svg)](https://github.com/anchore/grype)`

(or, more generically — )

`[![GitHub go.mod Go version](https://img.shields.io/github/go-mod/go-version/<USER>/<REPO>.svg)](https://github.com/<USER>/<REPO>)`

**Comment by luhring** [comment]
@wagoodman I defer to you and @alfredodeza , but we might want to leave this ticket open. While we handled the Go 1.16 move more thoroughly now, I think there might be outstanding work in the vein of preventing this in the future. What are your thoughts?

**Comment by alfredodeza** [comment]
This ticket wanted to address errors and messaging when unsupported Go versions are used. It would be ideal to either investigate that or fully acknowledge that it is not possible aside from documentation

**Comment by wagoodman** [comment]
I thought 301 accounted for this, did it not? The go.mod is the source of truth for what is supported in go tooling. This also affects the messaging for `go run` and `go build`:

with go.mod indicating 1.14:
```
❯ go version
go version go1.14.2 darwin/amd64
❯ go run main.go ubuntu:latest
# github.com/anchore/syft/syft/file
syft/file/digest_cataloger.go:90:38: hash.String undefined (type crypto.Hash has no field or method String)
syft/file/secrets_search_by_line_strategy.go:99:18: pattern.SubexpIndex undefined (type *regexp.Regexp has no field or method SubexpIndex)
```

with go.mod indicating 1.16:
```
❯ go version
go version go1.14.2 darwin/amd64
❯ go run main.go ubuntu:latest
# github.com/anchore/syft/syft/file
syft/file/digest_cataloger.go:90:38: hash.String undefined (type crypto.Hash has no field or method String)
syft/file/secrets_search_by_line_strategy.go:99:18: pattern.SubexpIndex undefined (type *regexp.Regexp has no field or method SubexpIndex)
note: module requires Go 1.16
```

With the new line `note: module requires Go 1.16` indicating the mismatch in go versions. From the issue description:

> Ideally (unsure if this is possible) something that prevents usage in unsupported Go versions, or that produces a better error

The go.mod bump alone does this ^.

Additionally, we've with 301 there is a badge that shows the supported version of go, derived from the go.mod:

<img width="922" alt="Screen Shot 2021-04-16 at 10 33 06 AM" src="https://user-images.githubusercontent.com/590471/115040226-34566d00-9e9f-11eb-8df5-19ae98d41cc8.png">

Are we saying that we want to take additional steps? I feel that the go.mod indications play nicely with go tooling and is good enough (where as documentation requires an additional manual update and is redundant to the go.mod).

**Comment by alfredodeza** [comment]
My main problem is that I looked at the error and it didn't say anything about my version of Go being incompatible. When I interact with most tooling from repositories in Github I seldom check badges to ensure that those will work for me or if it is related to the output from the error.

The examples you've provided which now include a "note: module requires Go 1.16" is what I was looking for. This issue can remain closed. Thanks @wagoodman !
