### ISSUE TITLE
CycloneDX format is broken in 0.7.0

### ISSUE THREAD

**Issue by damiencarol** [anchore/grype#288]
**What happened**:
The report generated by by Grype are not well formed XML for now.

**What you expected to happen**:
CycloneDX report well formed.

**How to reproduce it (as minimally and precisely as possible)**:
```
./grype docker:defectdojo/defectdojo-django:1.14.1 -q -o cyclonedx > dojo/unittests/scans/cyclonedx/dd_1_14_1.xml
```

**Anything else we need to know?**:

***Environment***:
- `grype version`: 
```
(.venv) [damien@damien dd]$ ./grype version
Application:          grype
Version:              0.7.0
BuildDate:            2021-01-28T14:03:23Z
GitCommit:            8344b8f0d3f61729cf0845c08b31f26103e21231
GitTreeState:         clean
Platform:             linux/amd64
GoVersion:            go1.14.14
Compiler:             gc
Supported DB Schema:  1
```
- OS (e.g: `cat /etc/os-release` or similar): Arch x64

***Part of the report that break***:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bom xmlns="http://cyclonedx.org/schema/bom/1.2" xmlns:bd="" xmlns:v="http://cyclonedx.org/schema/ext/vulnerability/1.0" version="1" serialNumber="urn:uuid:f3dfea9c-dad0-4384-bcc4-ec041015d36a">
  <metadata>
```
`xmlns:bd="" ` => invalid

**Comment by luhring** [comment]
@damiencarol Thanks for the report. Right now, the latest release of Grype is [v0.10.2](https://github.com/anchore/grype/releases/tag/v0.10.2). When I run `grype docker:defectdojo/defectdojo-django:1.14.1 -o cyclonedx`, I don't see `xmlns:bd=""` in the output. Would you mind running one more time with the latest release and let me know if you're able to reproduce this?

**Comment by damiencarol** [comment]
Awesome!
I switch my script to and it worked like a charm!
```shell
[damien@damien vulnerabilities]$ cat scripts/grype/test.sh 
wget -N https://github.com/anchore/grype/releases/download/v0.10.2/grype_0.10.2_linux_amd64.tar.gz -O grype.tar.gz
tar xf grype.tar.gz
chmod +x ./grype
./grype docker:python:3.6 -q -o cyclonedx > tests/scans/cyclonedx/grype.latest.xml
```
Seems version `0.10.2` is good. Closing this issue.
