### ISSUE TITLE
"No vulnerability database update available" when actually the check for an update was unsuccessful

### ISSUE THREAD

**Issue by luhring** [anchore/grype#310]
**What happened**:

Grype shows "No vulnerability database update available" when it _hasn't actually_ checked to see if a database update is available.

**What you expected to happen**:

If Grype is unable (for any reason) to check to see if a database update is available, it should report the failure to the user and exit non-zero.

**How to reproduce it (as minimally and precisely as possible)**:

1. For the sake of a clean environment, start a new container in which we'll run Grype: `docker run --rm -it ubuntu:latest bash`
2. Install `curl` if it's not already present: `apt-get update && apt-get install -y curl`
3. Install `grype`: `curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin`
4. Edit `/etc/resolv.conf` so that the system relies on an incorrect address for its DNS server. For example: `echo "nameserver 8.8.8.9" > /etc/resolv.conf`
5. Tell Grype to check for a database update: `grype db update`

Grype will show `No vulnerability database update available`, and its exit code will be `0`.

But in fact, **_Grype doesn't even have a local database yet_**. The same behavior can be witnessed if Grype has an _outdated_ database, too.

**Anything else we need to know?**:

There may exist other network-related failure modes that produce the same symptom, but this is the mode that I encountered today.

Also, **this impacts the security of the user** — because this output leads them to behave their Grype scans have considered the latest vulnerability data when this might not really be the case.

**Environment**:
- Output of `grype version`:

```
Application:          grype
Version:              0.11.0
BuildDate:            2021-04-22T21:51:14Z
GitCommit:            0a46e54aae837135f73d2ff18a84061189ee6f28
GitTreeState:         clean
Platform:             linux/amd64
GoVersion:            go1.16.3
Compiler:             gc
Supported DB Schema:  2
```

- OS (e.g: `cat /etc/os-release` or similar):

```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

(I've also seen this issue on **macOS** 11.2.3)

**Comment by Shanedell** [comment]
I am not able to reproduce this. I test by doing the below:

```bash
docker run -d --name grype-test --rm -it ubuntu:latest tail -f /dev/null
docker exec -it grype-test apt update
docker exec -it grype-test apt install curl -y
docker exec -it grype-test bash -c 'curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin'
docker exec -it grype-test grype db update
```

The final command outputs

```bash
 ✔ Vulnerability DB        [updated]
Vulnerability database updated to latest version!
```

Maybe this was fixed already and this issue wasn't tagged to close?

Tagging @tgerla @wagoodman to see if this should be closed.

**Comment by luhring** [comment]
I'm still able to reproduce this. @Shanedell a key step that looks like it's missing in your case was to intentionally break DNS resolution (as one example of how to cause a network issue for Grype) via editing `/etc/resolv.conf`.

I did have that step **out of order** in my original issue description, and I've just edited the description to be correct. If you run through those steps, you should still see this problem.
