### ISSUE TITLE
Add option for accessing registries without HTTPS

### ISSUE THREAD

**Issue by luhring** [anchore/grype#334]
Today, Grype can access OCI registries, but only via HTTPS (with [a few explicit exceptions made by the go-containerregistry library](https://github.com/google/go-containerregistry/blob/7e30746dde2f5a19b609f885dfef4e7b1d1503ad/pkg/name/registry.go#L74-L95)).

**Request:** Grype should allow a configuration option to let the user direct Grype to allow the HTTP scheme (as opposed to HTTPS) when communicating with the specified registry.

**Comment by luhring** [comment]
Once we implement this, we have an opportunity to **update Grype within our GitLab Container Scanning integration**. You'll see in the [Container Scanning docs](https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings) show that the setting `CS_REGISTRY_INSECURE` is supported by only Trivy, not Grype. So once Grype has this configuration option, we can open an MR with GitLab to support the related GitLab configuration option and propose a GitLab feature documentation update.

(The integration code itself lives here: https://gitlab.com/gitlab-org/security-products/analyzers/container-scanning)

**Comment by kzantow** [comment]
While working on this, I noticed there isn't currently a way to explicitly _disable_ https: https://github.com/google/go-containerregistry/blob/main/pkg/v1/remote/transport/ping.go#L77-L83 will that pose a problem?

**Comment by luhring** [comment]
> While working on this, I noticed there isn't currently a way to explicitly _disable_ https: https://github.com/google/go-containerregistry/blob/main/pkg/v1/remote/transport/ping.go#L77-L83 will that pose a problem?

I think that's okay, as long as a user that has **only an HTTP registry** (not HTTPS) can always use this option to successfully interact with their registry.

**Comment by mirekphd** [comment]
How to use this? The switch does / no longer exists according to my tests:
```
$ docker run --rm --name grype-tst anchore/grype:latest grype --insecure-use-http
unknown flag: --insecure-use-http

$ docker run --rm --name grype-tst anchore/grype:latest grype --help | grep insecure
$
```
More info:
```
$ docker run --rm -it --name grype-tst anchore/grype:latest version
Application:          grype
Version:              0.65.0
Syft Version:         v0.86.1
BuildDate:            2023-07-31T18:09:33Z
GitCommit:            c97048baa1595a481a26f7add8b18d59ec65838a
GitDescription:       v0.65.0
Platform:             linux/amd64
GoVersion:            go1.19.11
Compiler:             gc
Supported DB Schema:  5
```

**Comment by mirekphd** [comment]
Same problem with the corresponding env vars (REGISTRY_INSECURE_USE_HTTP=true, SYFT_REGISTRY_INSECURE_USE_HTTP=true, GRYPE_REGISTRY_INSECURE_USE_HTTP=true) although it is harder to prove:

```
$ docker ps | grep registry
8e42ffe1b243   registry:2                                    "/entrypoint.sh /etc…"   3 days ago   Up 3 days   0.0.0.0:5000->5000/tcp, :::5000->5000/tcp         registry

$ source ./scan-with-grype-dockerized.sh localhost:5000/mirekphd/ml-cache:20230731
[0000]  INFO grype version: 0.65.0
1 error occurred:
	* failed to catalog: unable to load image: unable to use OciRegistry source: failed to get image descriptor from registry: Get "https://localhost:5000/v2/": dial tcp 127.0.0.1:5000: connect: connection refused; Get "http://localhost:5000/v2/": dial tcp 127.0.0.1:5000: connect: connection refused
```

**Comment by mirekphd** [comment]
Unfortunately it is due to or related to the running as `root` requirement, which is also blocking any attempts to scan unpushed images (built locally but not available remotely), reported in https://github.com/anchore/grype/issues/1314

**Comment by mirekphd** [comment]
Even setting registry.insecure-use-http key to true in the config file did not help. Here's detailed log (from the `-vv` switch):

```
[0000] DEBUG application config:
configpath: /tmp/grype/grype-config.yml
[..]
registry:
  insecure-skip-tls-verify: true
  insecure-use-http: true
  auth: []

[0000]  INFO grype version: 0.65.0
[0000] DEBUG   ├── buildDate: 2023-07-31T18:09:33Z
[0000] DEBUG   ├── compiler: gc
[0000] DEBUG   ├── gitCommit: c97048baa1595a481a26f7add8b18d59ec65838a
[0000] DEBUG   ├── gitDescription: v0.65.0
[0000] DEBUG   ├── goVersion: go1.19.11
[0000] DEBUG   ├── platform: linux/amd64
[0000] DEBUG   ├── syftVersion: v0.86.1
[0000] DEBUG   └── version: 0.65.0
[0000] DEBUG gathering packages
[0000] DEBUG loading DB
[0000] DEBUG no socket address was found. Trying default address: /run/user/1177/podman/podman.sock from-lib=stereoscope
[0000] DEBUG looking for socket file: stat /run/user/1177/podman/podman.sock: no such file or directory from-lib=stereoscope
[0000] DEBUG image: source=OciRegistry location=localhost:5000/mirekphd/ml-cache:20230731 from-lib=stereoscope
[0000] DEBUG pulling image info directly from registry image="localhost:5000/mirekphd/ml-cache:20230731" from-lib=stereoscope
[0000] DEBUG no registry credentials configured, using the default keychain from-lib=stereoscope
1 error occurred:
	* failed to catalog: unable to load image: unable to use OciRegistry source: failed to get image descriptor from registry: Get "https://localhost:5000/v2/": dial tcp 127.0.0.1:5000: connect: connection refused; Get "http://localhost:5000/v2/": dial tcp 127.0.0.1:5000: connect: connection refused
```
Some checks:
```
$ docker images | grep localhost
localhost:5000/mirekphd/ml-cache                                      20230731                       878b29a95f79   4 days ago      22.9MB

$ docker ps | grep registry
8e42ffe1b243   registry:2                                    "/entrypoint.sh /etc…"   3 days ago   Up 3 days   0.0.0.0:5000->5000/tcp, :::5000->5000/tcp         registry
```

**Comment by mirekphd** [comment]
I think the relevant part of the log is (note: I'm running `anchore/grype` container with the `-u 1177` switch):
```
[0000] DEBUG no socket address was found. Trying default address: /run/user/1177/podman/podman.sock from-lib=stereoscope
```
