### ISSUE TITLE
grype is not consistent when scaning dir on disk 

### ISSUE THREAD

**Issue by yudong** [anchore/grype#338]
**What would you like to be added**:
grype can pick up RPM packages with vuln from /var/lib/rpm/Packages correctly when scanning a container image.
But running grype dir:/var/lib/rpm -o json on a host server would report 0 packages and 0 vuln.

**Why is this needed**:
Create known vulnerabilities for host server in addition to containers.

**Additional context**:

grype is amazing for containers. It would be great to reuse its existing capabilities on host server scan. So that user can have a single tool to meet both host and container SBOM/vuln scan needs.

**Comment by luhring** [comment]
This issue would likely get implemented via https://github.com/anchore/syft/issues/440, since Grype uses Syft to find packages on disk.

**Comment by wagoodman** [comment]
This was indeed implemented in anchore/syft#440 and released in [v0.15.0 of grype](https://github.com/anchore/grype/releases/tag/v0.15.0). Please feel free to reopen this issue if I'm wrong about that release covering the specific problem mentioned here!
