### ISSUE TITLE
Can we support path filtering for file system scanning？

### ISSUE THREAD

**Issue by song787** [anchore/grype#389]
**Why is this needed**:
Some paths do not need to be scanned, so they need to be excluded

Thanks

**Comment by luhring** [comment]
@song787 Good suggestion! We've talked about this, and this was even one possible solution to another issue (#183).

So we can better understand, what's the specific use case you have that would be addressed by this feature? (E.g. what kinds of paths don't need to be scanned?)

**Comment by song787** [comment]
@luhring ok, the case I'm currently facing is this: 
I put grype in a container of the k8s cluster and scan the host for vulnerabilities through the container. However, the error of permission problem occurs when scanning the `/proc` directory, as shown in the code. This problem occurred in the process of syft building the file tree of userinput. I tried to run the container in privileged mode, but it didn't work. At present, there is no way to solve it, so I consider whether I can mask the `/proc` directory through path filtering. Do you have any solutions? Thanks!

`/opt # ./grype2 dir:/opt/hostpath/proc  `
` ⠹ Vulnerability DB        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  [409 kB / 57 MB]`
` ⠹ Indexing /opt/hostpath/proc [file: /opt/hostpath/proc/30541/task/30803/net/dev_snmp6/veth785453e1]`
`[0004] ERROR failed to catalog: unable to determine resolver while cataloging packages: unable to index filesystem path="/opt/hostpath/proc": unable to access path="/opt/hostpath/proc/309/net": readdirent: invalid argument
`

**Comment by luhring** [comment]
@song787 Which version of Grype are you using?

I ask because we made a [change to not look at directories like `/proc`](https://github.com/anchore/syft/pull/442) a while back. This was incorporated into Syft v0.19.0, which was brought into Grype as of Grype v0.14.0.

**Comment by song787** [comment]
@luhring My current version is Grype v0.15.0.
Have you blocked the `/proc` directory in v0.15.0?
ok, I just tested it. The `/proc` directory has indeed been masked by local scanning on the host. However, when you put Grype in the container and scan the host through the mount directory, Grype will still scan the `/proc` directory of the host.

**Comment by luhring** [comment]
Thanks for the info! Just so I understand the use case: You're running Grype in a container, in which you've mounted `/proc` from the host as `/proc` in the container, and you're having Grype perform a directory scan?

Also, are you able to share the exact Grype command you're running?

**Comment by song787** [comment]
@luhring 
Grype runs in a container of the k8s cluster. and mount the root directory ` / ` of the host computer in the `/opt/hostpath` directory of the container.Run grype : `./grype dir:/opt/hostpath`. When the `/opt/hostpath/proc` directory is scanned, it will be terminated due to that error

**Comment by wagoodman** [comment]
Just a quick comment to link --this seems pseudo-related to https://github.com/anchore/syft/issues/221 . Syft is the dependency here that is fed many (maybe all?) of the input requests for obtaining the content scanned. If we choose to expose this as a CLI/config option here, odds are that the enhancement here should follow the enhancement proposed in https://github.com/anchore/syft/issues/221 .

**Comment by luhring** [comment]
Thanks for the context, @song787 — this helps!

And good link @wagoodman — I agree it makes sense to tie these together.

**Comment by kzantow** [comment]
This is blocked pending release with https://github.com/anchore/syft/pull/695
