### ISSUE TITLE
Allow for ingestion of SPDX SBOM documents as input

### ISSUE THREAD

**Issue by wagoodman** [anchore/grype#395]
Today we allow for the syft JSON document as an SBOM input. It would be ideal to additionally interop with tools that produce SPDX documents and allow that as input into grype for vulnerability scanning.

**Comment by wagoodman** [comment]
Could be closely related to https://github.com/anchore/syft/issues/400 and may have architectural changes/concerns. (we should try and tackle SBOM ingestion for syft and grype together)

**Comment by luhring** [comment]
Implementation idea (RFC): In addition to ingesting SPDX in general, we've mentioned the notion of _piping_ SPDX into Grype (or Syft, per https://github.com/anchore/grype/issues/395#issuecomment-903769157). This could get tricky if we accept multiple formats (e.g. Syft + SPDX) and have to try to detect what we're receiving in the byte stream (not impossible, though).

Many tools have a convention of using `-` to refer to a command's `stdin`. We could use this in combination with our "schemes" system to allow the user to instruct the tool explicitly on how to interpret the inbound bytes.

E.g.: `cat my-sbom.spdx | grype spdx:- ...`

**Comment by luhring** [comment]
This will be unblocked once https://github.com/anchore/syft/issues/556 is closed

**Comment by wagoodman** [comment]
This same comment applies https://github.com/anchore/grype/issues/481#issuecomment-996972824

**Comment by kzantow** [comment]
An associated Syft PR can be found here: https://github.com/anchore/syft/pull/738
