### ISSUE TITLE
Match type should appear in match details report section

### ISSUE THREAD

**Issue by wagoodman** [anchore/grype#400]
Today there is a `match.Type` field that classifies the kind of match (e.g. ExactDirect or ExactIndirect). This is not being exposed within the `.matchDetails` JSON section for each match:
```json
   "matchDetails": [
    {
     "matcher": "rpmdb-matcher",
     "searchedBy": {
      "distro": {
       "type": "centos",
       "version": "8"
      },
      "namespace": "rhel:8"
     },
     "found": {
      "versionConstraint": "none (rpm)"
     }
    }
   ],
```

1. Is the omission of the type intentional?
2. If not, is there a reason why it should not be added? (e.g. values are not finalized, doesn't help the user, etc)

My vote is that having this information is helpful in qualifying the match and helping tell the story in how the match was made.

**Comment by westonsteimel** [comment]
Match type has been surfaced in the `matchDetails` section for some time now, so I'm going to close this one
