### ISSUE TITLE
Need AlmaLinux OS Scan support enhancement

### ISSUE THREAD

**Issue by srbala** [anchore/grype#412]
**What happened**:
#360 Feature request to add AlmaLinux OS Scan support and its been resolved. AlmaLinux is variant of RedHat, security scan should return those too.

`docker run --rm -it anchore/grype redhat/ubi8` returns 160 entries
`docker run --rm -it anchore/grype almalinux:8` returns 2 entries

**What you expected to happen**:
number of security entry should be equal (some time more, when fix is released by RedHat and yet to released by AlmaLinux usually 1-5 days

**How to reproduce it (as minimally and precisely as possible)**:
Given above.

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:
current (v0.17.0)

- OS (e.g: `cat /etc/os-release` or similar):
```sh
NAME="AlmaLinux"
VERSION="8.4 (Electric Cheetah)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.4 (Electric Cheetah)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:almalinux:almalinux:8.4:GA"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.4"
```

**Comment by luhring** [comment]
Hi @srbala — this is a good catch, thanks for pointing this out to us. It looks like there's more work to do before we can claim to support AlmaLinux.

**Comment by srbala** [comment]
I have created number of PRs related in https://github.com/anchore/anchore-engine/pull/1326, this is ping back

**Comment by spiffcs** [comment]
With alma linux supported in syft and grype I'm going to close this issue. We'll keep track of any issues or follows for this on the engine specific issue:
https://github.com/anchore/anchore-engine/issues/1299
