### ISSUE TITLE
We either need an output to file option, or a Docker image that has a shell

### ISSUE THREAD

**Issue by jdurzi** [anchore/grype#418]
**What would you like to be added**:
An official docker image for Grype that either has a shell, or an option to output findings to a file.

**Why is this needed**:
We're using Kubernetes native tooling for CI/CD (Tekton), and there isn't really an option to use Grype's official docker containers, because we need to output to a file, and it only outputs to stdout. Of course, an easy fix would be to just forward STDOUT to a file, but you can't do that in the docker container, because it has no shell.

There was a PR for a solution for this in Tekton but it's been closed and no ETA: https://github.com/tektoncd/pipeline/pull/3103
Similar situation with k8s: https://github.com/kubernetes/kubernetes/issues/94892

**Comment by wagoodman** [comment]
Agreed, this will be implemented in grype within the next few weeks 👍 . Checkout the `output-to-file` branch that has `--file`/`-f` for a preview.

(note: this is a dup of https://github.com/anchore/grype/issues/207)

**Comment by wagoodman** [comment]
Added the additional context to https://github.com/anchore/grype/issues/207#issuecomment-934482630 and will track progress in #207
