### ISSUE TITLE
Multiple configuration files

### ISSUE THREAD

**Issue by arothian** [anchore/grype#449]
**What would you like to be added**:
Currently, it looks like Grype takes the first config file it finds based on the [search list](https://github.com/anchore/grype#configuration) in the README.

With the recent feature release for ignoring matches, it would be great if multiple config files would be read and merged, with precedence based on the existing search list order.

This would allow having one configuration file at the user level, which can control settings around the db, update checks, etc and then allow creating a config file in individual code repos with ignore settings for accepted vulnerabilities or false positives.

**Why is this needed**:

Specifying grype config in a code repo so as to ignore false positives requires duplication of any "global" configuration that you would like to apply to all grype invocations at the user/system level.

Cheers and nice work on this tool.

**Comment by kzantow** [comment]
@arothian it should probably be documented more clearly in the config section, but it's possible to pass a configuration file using the `-c` option, e.g. `grype -c /path/to/config.yml`

**Comment by spiffcs** [comment]
@arothian I think we're going to stay cautious on the complexity here and not support merging config files together. I appreciate the issue you filed here and do want to solve your pain. Is there a way the "global" config could be represented as a common export file of environment variables while the ignore config is passed as an argument?

**Comment by arothian** [comment]
Hi @spiffcs , that might potentially work. I'm not currently using grype in the same manner anymore. No issues if you want to close this.

**Comment by spiffcs** [comment]
Thanks a million!
