### ISSUE TITLE
Homebrew is showing warnings for grype installation

### ISSUE THREAD

**Issue by wagoodman** [anchore/grype#476]
**What happened**:
When running `brew upgrade <package>` the following warnings appeared:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the anchore/syft tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/anchore/homebrew-syft/syft.rb:9

Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the anchore/grype tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/anchore/homebrew-grype/grype.rb:9
```

**What you expected to happen**:
There shouldn't be warnings for our homebrew formulas on any brew command.

**Comment by sticksen** [comment]
+1

**Comment by spiffcs** [comment]
Is this an upstream issue with consuming an earlier version of goreleaser? 

I just bumped and generated the dist locally for a snapshot release and still saw `bottle :unneeded` in the output. Either we wait for the releaser code to be updated or we modify the .rb files post-release to remove this line.

**Comment by kkovaletp** [comment]
This issue was fixed some time ago, but returned back. Just letting you know...

**Comment by DonHege** [comment]
I encountered the same. 

Homebrew 3.3.8
Homebrew/homebrew-core (git revision e3aee5b90d8; last commit 2021-12-14)
Homebrew/homebrew-cask (git revision 947f995586; last commit 2021-12-14)

On MacOS 10.15.7

**Comment by spiffcs** [comment]
Correct - We're waiting for the latest upcoming goreleaser release `v1.2` because of some support we need for our osx signing process. Apologies for the run around on updating this each time we do a release.

**Comment by luhring** [comment]
@spiffcs Can this be closed?
