### ISSUE TITLE
Use existing registry authentication such as Docker config

### ISSUE THREAD

**Issue by luhring** [anchore/grype#478]
Similar to anchore/syft#502, it would be great not to necessitate registry credentials to be specified to Grype via Grype's config, since users likely already have credentials available locally (such as via a Docker config or a credential helper). Let's allow for Grype to identify existing registry credentials and bring them automatically into Grype's config such that any authenticated registry operations within Grype can benefit from this pre-existing authenticated state.

This makes Grype easier to use with private images without asking the user to do any work upfront. And it helps Grype fit in better to workflows like in Tekton, where registry credentials are already mounted into running containers that Grype could use.

cc: @nadgowdas

**Comment by spiffcs** [comment]
See this comment:
https://github.com/anchore/syft/issues/502#issuecomment-957017480
