### ISSUE TITLE
ossf/scorecard vulnerabilities fix tracking issue

### ISSUE THREAD

**Issue by developer-guy** [anchore/grype#482]
**What would you like to be added**:

We recently ran the `ossf/scorecard`[^1] over the `Grype` project, found some vulnerabilities, here is the output of the scan:

```shell
$ docker run -e GITHUB_AUTH_TOKEN=$GITHUB_TOKEN gcr.io/openssf/scorecard:stable --repo https://github.com/developer-guy/grype
```
![Screen Shot 2021-10-26 at 01 05 31](https://user-images.githubusercontent.com/16693043/138885484-7c80755d-295f-430f-ac60-2b348bde877a.png)
![Screen Shot 2021-10-26 at 01 05 42](https://user-images.githubusercontent.com/16693043/138885501-a291e135-c8dd-436b-b038-7532f34e55c1.png)

**Why is this needed**:

To make Grype more secure.

**Additional context**:
[^1]: https://github.com/ossf/scorecard

cc: @wagoodman @luhring @dentrax

**Comment by kzantow** [comment]
We have since added scorecard and have individual issues to address the lower scores, so I'm going to close this one. Please reopen if you deem it necessary!
