### ISSUE TITLE
Grype seems to hang up when use in a Azure DevOps pipeline

### ISSUE THREAD

**Issue by trhumphries** [anchore/grype#492]
**What happened**:
I've integrated Grype into our ADO pipeline when building container for AKS. when it executes it hangs up and the pipeline times out after 60 minutes

**What you expected to happen**:
I expected it to produce the vulnerability output
**How to reproduce it (as minimally and precisely as possible)**:
It's integrated as a template:

parameters:
  imageName: ''
  imageVersion: ''
  imagePath: ''

steps:
- bash: |
    brew tap anchore/grype
    brew install grype
  displayName: Install grype 
- bash: |
        grype ${{ parameters.imageName }} -vv
That's called right after the container has been built
**Anything else we need to know?**:
I also use Syft to generate an SBOM and it works as expected. I've tried having Grype scan the local container image  as an oci directory and the remove container image in Azure Container registry hangs in both cases.

**Environment**:
- Output of `grype version`: 024.0
- OS (e.g: `cat /etc/os-release` or similar): Ubuntu

**Comment by luhring** [comment]
Thanks @trhumphries! It would be tremendously helpful if we could test with an image locally to reproduce this on our developer machines. That would help us to debug the issue.

**Are you able to provide one of the following?**

1. Access to the exact image you're atttempting to scan, or
2. Access to a different image, that's similar enough where the behavior can still be reproduced

**Comment by trhumphries** [comment]
Here's an sbom generated with Syft note I had to change the extension to txt from sbom to be able to upload it.
Also I've noticed that before the ADO process timeout the last line in the log is:
[***;9***m[***5][***m [***;32m INFO[***m Updated vulnerability DB to version=3 built="2***21-11-***4 ***8:13:46 +*** UTC"
then after it times out its:
[***;9***m[***5][***m [***;32m INFO[***m Updated vulnerability DB to version=3 built="2***21-11-***4 ***8:13:46 +*** UTC"
1 error occurred:
	* failed to catalog: unable to process input for scanning: 'sbom:./atlas-backup.sbom'

its as if for some reason the bash running the grype can't detect that its ended.

[atlas-backup.txt](https://github.com/anchore/grype/files/7486291/atlas-backup.txt)

**Comment by luhring** [comment]
It looks like that SBOM is in _CycloneDX_ format. We don't yet support scanning CycloneDX SBOMs, but that's coming very soon, and it's tracked in this issue: https://github.com/anchore/grype/issues/481

Can you try again but instead using Syft's native JSON format? (using `syft -o json ...`)

**Comment by trhumphries** [comment]
Same result with a json formatted file.

**Comment by luhring** [comment]
Can you upload the Syft JSON file?

And it's the same error message from your previous message? `failed to catalog: unable to process input for scanning: 'sbom:./atlas-backup.sbom'`

My goal here is to get to a point where I can produce this on my computer. **If you have a container image you can share** that exhibits this behavior, that'd be ideal!

**Comment by trhumphries** [comment]
Not sure wha change. However, I ran my Azure Pipeline this morning to collect the json SBOM to send you a copy and Grype no longer hangs up. It generate the report as it should.

**Comment by luhring** [comment]
@trhumphries That's great news! In that case, we can close this issue? And we can always re-open if you see the problem crop up again.
