### ISSUE TITLE
to integrate OPA Gatekeeper's new external data feature by providing grype-provider

### ISSUE THREAD

**Issue by developer-guy** [anchore/grype#503]
**What would you like to be added**:

Gatekeeper is a customizable admission webhook for Kubernetes that enforces policies executed by the Open Policy Agent (OPA), a policy engine for Cloud Native environments hosted by CNCF. 

We had talked about the new design called `ExternalData` in OPA Gatekeeper with @sozercan which is one of the maintainers of the OPA Gatekeeper project in the issue opened for cosign[^1]. The main goal of this feature is to provide better usability and integrability of 3rd providers with OPA Gatekeeper instead of just using `http.send` built-in function in Rego.

**Why is this needed**:

It'd be nice to integrate with OPA Gatekeeper and provide the ability to scan container images with Grype.

**Additional context**:

Here is the `dummy-provider` to see what the provider looks like, thanks to @sozercan.[^2]

[^1]: https://github.com/sigstore/cosign/issues/655
[^2]: https://github.com/open-policy-agent/gatekeeper/tree/master/test/externaldata/dummy-provider

cc: @dentrax @luhring @wagoodman

**Comment by developer-guy** [comment]
We should enhance this kind of provider thing by using Syft also. How? Syft can generate an SBOM for the container images that we want to validate. Then we can use Grype to analyze this SBOM file to create another provider for it. For example, it might be `syft-provider` idk.

**Comment by tibers** [comment]
https://github.com/boxboat/grypeadmissioncontroller I wrote this and got permission to open source it. This might scratch your itch? :)

**Comment by spiffcs** [comment]
Wow @tibers this is awesome. Thanks for maintaining the project I saw it was on grype v0.48.0. @developer-guy does this "scratch the itch" or are we still interested in a specific provider for OPA that leverages grype?

**Comment by dasiths** [comment]
> https://github.com/boxboat/grypeadmissioncontroller I wrote this and got permission to open source it. This might scratch your itch? :)

Awesome. It's very similar to https://github.com/aquasecurity/trivy-enforcer.

**Comment by tibers** [comment]
> Awesome. It's very similar to https://github.com/aquasecurity/trivy-enforcer.

No updates in 3 years though? It would be ironic if it couldn't deploy itself because... it was too old and had vulnerabilities. :(

**Comment by tgerla** [comment]
Hi everyone, I am going to go ahead and close this issue since I don't believe it's exactly a feature request or bug for Grype, but instead for the OPA gatekeeper. I would suggest maybe opening an issue over there. Thanks and please let us know if you need anything from us to help.
