### ISSUE TITLE
add documentation about air gap installation support

### ISSUE THREAD

**Issue by developer-guy** [anchore/grype#509]
**What would you like to be added**:

We had talked with @luhring @wagoodman related to this and decided to add documentation about the air gap installation support of Grype.

**Why is this needed**:

To give information to people who might be interested in setting up Grype in an air gap environment.

**Additional context**:

**Comment by developer-guy** [comment]
Found this. 

https://github.com/anchore/grype#offline-and-air-gapped-environments

**Comment by luhring** [comment]
Let's re-open this, with the goal of providing better guidance to folks working in air-gapped environments

**Comment by luhring** [comment]
I think there might be two separate workflows we could outline for users:

1. Fetching the database in advance, and ensuring that it's placed in Grype's cache directory ahead of running Grype.
2. Letting Grype fetch the database on-the-fly, but using a different endpoint for retrieving the database (such as on a private network). Here, we can talk about customizing the database update URL and configuring Grype to use a custom CA (if needed).

**Comment by spiffcs** [comment]
@developer-guy is the current documentation sufficient, or do you have any other suggestions for improvement? Otherwise I think we can close this issue

**Comment by kzantow** [comment]
Since this hasn't had a response in a while, and there seems to be sufficient documentation, I'm going to close this issue. But also note that we have plans to publish a docker image with embedded database as well, which may help air-gapped installs too.
