### ISSUE TITLE
Could not create temp dir: mkdir /tmp/stereoscope-cache*: no space left on device

### ISSUE THREAD

**Issue by frafra** [anchore/grype#533]
**What happened**:
Failure when fetching an image, as no more space on /tmp is available.

**What you expected to happen**:
Improved error handling, with the suggestion of using an option to choose a different temporary folder.

**How to reproduce it (as minimally and precisely as possible)**:
Fetch a large image over a small /tmp folder.

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`: 0.27.0
- OS (e.g: `cat /etc/os-release` or similar): Ubuntu 18.04.6 LTS

**Comment by spiffcs** [comment]
Thanks for the issue @frafra. We'll take a look at making this configurable with an option in the case that /tmp is no a viable option for fetching large images.

If you could provide an image that you see this failing for that would be great. If you can't provide the image, than a ballpark of what size you're seeing this behavior at would help so we have a starting point to see where the pain is.

**Comment by frafra** [comment]
My `/tmp` is 2 GB. `geonode/geonode` is ~1.3 GB. It fails when saving the image to disk.

**Comment by luhring** [comment]
>suggestion of using an option to choose a different temporary folder

Hi @frafra! You should be able to control the tmp directory with the `TMPDIR` environment variable. For example:

```shell
TMPDIR='~/my/tmp' grype my-image:latest
```

Can you try this and let us know if that works for you?

(Note: Related to https://github.com/anchore/syft/issues/552)

**Comment by frafra** [comment]
`mkdir -p "$HOME/tmp" && TMPDIR="$HOME/tmp" grype geonode/geonode` works :)

**Comment by luhring** [comment]
Great! 🎉
