### ISSUE TITLE
anchore/grype crit unable to find '' - use 'latest'

### ISSUE THREAD

**Issue by bajanray** [anchore/grype#542]
When running the installation script: 

`curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin`

I get this error:

`anchore/grype crit unable to find '' - use 'latest' or see https://github.com/anchore/grype/releases for details`

Don't know what I'm supposed to do next after that.  Any help would be greatly appreciated.

**Comment by kzantow** [comment]
This looks to be effectively the same as: https://github.com/anchore/syft/issues/672 . @bajanray could you provide the OS you are using? and any other information such as the shell / if it's a VM / etc.? Thanks!

**Comment by kzantow** [comment]
@bajanray also, could you please send the output of:
```shell
sh --version
```
and:
```shell
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -x
```
Thanks!

**Comment by bajanray** [comment]
Keith

My OS is Windows 10 but I am running Cygwin 3.3.3

Output from sh --version:

$ sh --version
GNU bash, version 4.4.12(3)-release (x86_64-unknown-cygwin)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

I have attached the file curl_output.txt which has the results from:
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -x


Thanks
________________________________

**Comment by luhring** [comment]
@bajanray What output do you get when you run `curl --version`? And also, when you run `stat /usr/local/bin`?

**Comment by bajanray** [comment]
$ curl --version
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: 2017-11-14, security patched: 2019-11-05
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL


$ stat /usr/local/bin
  File: /usr/local/bin
  Size: 0               Blocks: 0          IO Block: 65536  directory
Device: 70f77e10h/1895267856d   Inode: 2814749767568187  Links: 1
Access: (0755/drwxr-xr-x)  Uid: (197609/     ray)   Gid: (197121/    None)
Access: 2021-12-15 03:36:43.407219800 -0500
Modify: 2021-12-14 20:30:27.181289900 -0500
Change: 2021-12-14 20:30:27.181289900 -0500
 Birth: 2021-12-14 20:30:27.181289900 -0500
________________________________

**Comment by luhring** [comment]
@wagoodman Do you think it's possible this might be resolved when the upcoming changes to `install.sh` land?

**Comment by kaser91** [comment]
I have a problem when installing
I get the error as shown here
curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
[info] checking github for the current release tag
[info] fetching release script for tag='v0.33.1'
[info] checking github for the current release tag
[info] using release tag='v0.33.1' version='0.33.1' os='linux' arch='amd64'
install: cannot create regular file '/usr/local/bin/grype': Permission denied
[error] failed to install graype

Thanks

**Comment by wagoodman** [comment]
@kaser91 The main problem is here:
```
install: cannot create regular file '/usr/local/bin/grype': Permission denied
```
Note that `'/usr/local/bin` is not user writable by default, which means that you will have to take some additional action:
- install to another location and append that location to `PATH`: `curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b ~/bin` and `export PATH=~/bin:PATH`
- install to another location and copy into `/usr/local/bin`: `curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b ~/bin` and `sudo cp ~/bin/grype /usr/local/bin`
- install as root (not recommended)

Shout out if you have any additional questions on this

**Comment by wagoodman** [comment]
@wagoodman I haven't tried the install.sh out on the latest setup with Cygwin, however, I do think it should be covered. I can get a windows box / vm to try it out when I get some extra cycles.
