### ISSUE TITLE
Unable to download vulnerability database after installation due too checksum mismatch

### ISSUE THREAD

**Issue by GilbertK99** [anchore/grype#544]
What  happened:
After download, i issued the command grype update db and received the following error. 
"unable to update vulnerability database: unable to update vulnerability database: unable to download db: Checksums did not match for /tmp/getter233760951/archive.
Expected: 70277bb26084c7276ed31ab176ced722484ebd232ce25d332ec4dddd07f32edc
Got: 4c89a527e0d50749dee7aabd199e4c94eef9878f721ccc644a4f1315d6ef13e2
*sha256.digest"

What did you expect to happen:
I expected the vulnerability database to be updated

Environment:
Application:          grype
Version:              0.27.2
Syft Version:         v0.32.2
BuildDate:            2021-12-14T17:58:17Z
GitCommit:            81a16c4142523f455d76663e7ec7d379e3f7a73d
GitTreeState:         clean
Platform:             linux/amd64
GoVersion:            go1.16.11
Compiler:             gc
Supported DB Schema:  3

**Comment by GilbertK99** [comment]
What  happened:
After download, i issued the command grype update db and received the following error. 
"unable to update vulnerability database: unable to update vulnerability database: unable to download db: Checksums did not match for /tmp/getter233760951/archive.
Expected: 70277bb26084c7276ed31ab176ced722484ebd232ce25d332ec4dddd07f32edc
Got: 4c89a527e0d50749dee7aabd199e4c94eef9878f721ccc644a4f1315d6ef13e2
*sha256.digest"

What did you expect to happen:
I expected the vulnerability database to be updated

Environment:
Application:          grype
Version:              0.27.2
Syft Version:         v0.32.2
BuildDate:            2021-12-14T17:58:17Z
GitCommit:            81a16c4142523f455d76663e7ec7d379e3f7a73d
GitTreeState:         clean
Platform:             linux/amd64
GoVersion:            go1.16.11
Compiler:             gc
Supported DB Schema:  3

**Comment by spiffcs** [comment]
Hey @GilbertK99 here is a thread in the community channel where we helped debug a similar problem:
https://anchorecommunity.slack.com/archives/C027JE5M345/p1639512986077800

Please try these steps:
```
```

**Comment by GilbertK99** [comment]
Thank you! I tried updating again and it worked without the above solution.
