### ISSUE TITLE
Unable to run scan against a directory for droplet vulnerability

### ISSUE THREAD

**Issue by tanjoht** [anchore/grype#545]
**What happened**:
While trying to run a scan against a directory, it does not find the droplets to scan:
grype dir:droplet_test
 ✔ Vulnerability DB        [no update available]
 ✔ Indexed droplet_test    
 ✔ Cataloged packages      [0 packages]
 ✔ Scanned image           [0 vulnerabilities]

Referincing the file directly work as expected:
worker/511f87bb-cf57-41bc-baf7-073ebcac9ff3:~# grype droplet_test/droplet_fa1c116c-e626-48b4-93fd-4bf5a2e07dea.tgz 
 ✔ Vulnerability DB        [no update available]
 ✔ Indexed /tmp/syft-archive-contents-726593847 
 ✔ Cataloged packages      [115 packages]
 ✔ Scanned image           [10 vulnerabilities]

**What you expected to happen**:
Grype should search for all droplets within a directory and scan them

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`: 
grype version
Application:          grype
Version:              0.27.2
Syft Version:         v0.32.2
BuildDate:            2021-12-14T17:58:17Z
GitCommit:            81a16c4142523f455d76663e7ec7d379e3f7a73d
GitTreeState:         clean
Platform:             darwin/amd64
GoVersion:            go1.16.11
Compiler:             gc
Supported DB Schema:  3

- OS (e.g: `cat /etc/os-release` or similar): ubuntu xenial

**Comment by luhring** [comment]
Hi @tanjoht 👋  Just to make sure I understand: When you say "droplet", what are you referring to?

Grype uses [Syft](https://github.com/anchore/syft) to discover what packages exist in a given scan target (e.g. a directory). Syft doesn't yet unpack `.tgz` files, but that seems like it should be addressed via https://github.com/anchore/syft/issues/246

**Comment by tanjoht** [comment]
Hi @luhring, thanks for the response. Droplet's is referring to the packaged tarball.

**Comment by luhring** [comment]
Got it! I think this is referring to the same functionality as described in https://github.com/anchore/syft/issues/246, so let's track progress on this enhancement there.
