### ISSUE TITLE
allow recursive scanning of packages in a directory

### ISSUE THREAD

**Issue by tanjoht** [anchore/grype#546]
**What would you like to be added**:
Allow the tool to recursively scan a specified directory and scan all packages within the directory.

**Why is this needed**:
In a cloud foundry deployment, many apps are compiled and packaged into a common directory. It would be useful to scan  a specified directory for vulnerabilities on all packages.

**Additional context**:
Note: the packages may not have a tar/tgz extension even though they are tar compressed (they have no extensions)

**Comment by luhring** [comment]
Hi @tanjoht — Grype uses [Syft](https://github.com/anchore/syft) to find packages in a directory. Syft already scans for packages recursively in a directory. Syft doesn't yet support unpacking `.tgz` files found within a directory. If I'm understanding correctly, this is the same as what's being requested in your other issue https://github.com/anchore/grype/issues/545 — do I have that right?

**Comment by tanjoht** [comment]
Hi @luhring, when i mention packages, i am referring to the tarball. For example would like to run grype against a directory as so:

grype dir:/directory

where /directory contains
/directory/package_a/tarball_a
/directory/package_b/tarball_b
/directory/package_c?tarball_c

and have it scan all 3 tarballs (no need to unpack). Also note that there isn't a .tar or tgz on these tarballs

**Comment by luhring** [comment]
If I'm understanding correctly, this is an existing feature request: https://github.com/anchore/syft/issues/246 We'll track progress on this feature in that issue.

I'll close for now, but please let me know if I've misunderstood the intent of this issue!
