### ISSUE TITLE
Grype stucks on some images

### ISSUE THREAD

**Issue by tsunamaru** [anchore/grype#549]
**What happened**:
On some images grype is infinity showing "Loading image" - "Saving image to disk" and not responding to SIGTERM.
![image](https://user-images.githubusercontent.com/37580200/146381679-4aad57f1-a379-4691-81a6-c81df58d1c13.png)

**What you expected to happen**:
Scan be done :)

**How to reproduce it (as minimally and precisely as possible)**:
I can send you example image by any private means (it contains company private code and thus can't be uploaded to public share or registry, sorry). Ideally, if you give me some email for contact.

**Anything else we need to know?**:
No, I don't think so.

**Environment**:
- Output of `grype version`:
```
Application:          grype
Version:              0.27.2
Syft Version:         v0.32.2
BuildDate:            2021-12-14T17:58:17Z
GitCommit:            81a16c4142523f455d76663e7ec7d379e3f7a73d
GitTreeState:         clean
Platform:             linux/amd64
GoVersion:            go1.16.11
Compiler:             gc
Supported DB Schema:  3
```
- OS (e.g: `cat /etc/os-release` or similar):
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by wagoodman** [comment]
We're releasing a fix for a recent performance regression in syft https://github.com/anchore/syft/issues/696 . A grype release will be out within the hour with the fix as well.

**Comment by tsunamaru** [comment]
Thank you for quick response @wagoodman. I'll test new version as soon as it comes out and let you know if I still experiencing this issue.

**Comment by tsunamaru** [comment]
@wagoodman unfortunately, still facing same issue on grype 0.27.3

**Comment by tsunamaru** [comment]
As the issue is not related to grype directly but syft, I'm closing this issue to recreate on syft repository.
