### ISSUE TITLE
Error when scanning a single file (e.g. zip, war, etc.) and using JSON output format

### ISSUE THREAD

**Issue by nto4** [anchore/grype#554]
**What happened**:
searched *war  files -o json give me that error

```
file ROOT.war
ROOT.war: Zip archive data, at least v1.0 to extract

 grype blabla/ROOT.war -o json
 ✔ Vulnerability DB        [no update available]
 ✔ Indexed blabla/ROOT.war
 ✔ Cataloged packages      [284 packages]
 ✔ Scanned image           [336 vulnerabilities]
[0006] ERROR unable to show grype-vulnerability-scanning-finished event: unable to show vulnerability report: unsupported source: source.Metadata

```

cyclonedx and table working correctly 

but if im unzip this war file and run 

`grype blabla/ROOT -o json`
working correctyl 

**Environment**:

```
echo "$BASH_VERSION"
5.1.0(1)-release
```

- Output of `grype version`:
- OS (e.g: `cat /etc/os-release` or similar):

```
grype version
Application:          grype
Version:              0.27.3
Syft Version:         v0.33.0
BuildDate:            2021-12-16T15:11:16Z
GitCommit:            4f964c4ee26ad01a80b8bcffb6bf23c0afb71d09
GitTreeState:         clean
Platform:             linux/amd64
GoVersion:            go1.16.12
Compiler:             gc
Supported DB Schema:  3

cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic


```

**Comment by luhring** [comment]
@nto4 Great find, thank you!

**Comment by luhring** [comment]
Adding my own minimal reproduction steps:

1. `mkdir folder`
2. `( cd ./folder && curl -O https://raw.githubusercontent.com/anchore/stereoscope/main/go.mod )` (the problem has nothing to do with stereoscope or its `go.mod`, I'm just picking it arbitrarily so there's some catalog data 😃 )
3. `zip -r ./folder ./folder`
4. `grype -o json ./folder.zip` (or alternatively, `grype -o json file:./folder.zip`)

```
...
ERROR unable to show grype-vulnerability-scanning-finished event: unable to show vulnerability report: unsupported source: source.Metadata
```

**Comment by tomaecoward-inawisdom** [comment]
Is this fixed? 
Seeing this issue in 

grype version  
Application:          grype
Version:              0.27.3
Syft Version:         v0.33.0
BuildDate:            2021-12-16T15:11:16Z
GitCommit:            4f964c4ee26ad01a80b8bcffb6bf23c0afb71d09
GitTreeState:         clean
Platform:             darwin/amd64
GoVersion:            go1.16.12
Compiler:             gc
Supported DB Schema:  3





grype temp.zip -o json     
 ✔ Vulnerability DB        [no update available]
 ✔ Indexed /var/folders/_t/bqxm7wsn7k1bpl0y5l1g8bw40000gp/T/syft-archive-contents-153374829  ✔ Cataloged packages      [32 packages]
 ✔ Scanned image           [2 vulnerabilities]
[0006] ERROR unable to show grype-vulnerability-scanning-finished event: unable to show vulnerability report: unsupported source: source.Metadata



When unpacking and scanning within the location, works OK

**Comment by luhring** [comment]
@tomaecoward-inawisdom This was merged but hasn't been released yet I'm expecting a new release to come out today.
