### ISSUE TITLE
Enhancement request for scanner to be able to review rpm packages

### ISSUE THREAD

**Issue by PyOctoCat** [anchore/grype#570]
Enhancement request for the scanner to be able to review rpm packages. Impressed at how it scans other repositories, but it seems to miss RPMs and OVAs.

**Comment by kzantow** [comment]
@PyOctoCat are you referring to RPM packages on disk (e.g. `nodejs-devel-10.13.0-2.el7.x86_64.rpm`)?

**Comment by kzantow** [comment]
@PyOctoCat also, I'm going to split this into 2 issues, unless you object: one for RPM and one for OVA

**Comment by kzantow** [comment]
Sibling issue: https://github.com/anchore/grype/issues/573

**Comment by PyOctoCat** [comment]
yes I think two tickets would make since. And that rpm example would be what I think would be needed. Ability to run a static scan. Thanks for looking at this.
