### ISSUE TITLE
Issue in Installation. err: anchore/grype err hash_sha256_verify unable to find checksum 

### ISSUE THREAD

**Issue by PlaxoGhouse** [anchore/grype#577]
_$ curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh \| sh -s -- -b /usr/local/bin_

anchore/grype info checking GitHub for latest tag
anchore/grype info found version: 0.28.0 for v0.28.0/windows/amd64                                                                                    anchore/grype err hash_sha256_verify unable to find checksum for '/tmp/tmp.QojFZq6rDd/grype_0.28.0_windows_amd64.zip' in '/tmp/tmp.QojFZq6rDd/grype_0 .28.0_checksums.txt'

$ sh --version
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ curl --version
curl 7.63.0 (x86_64-w64-mingw32) libcurl/7.63.0 OpenSSL/1.1.1a (WinSSL) zlib/1.2.11 libidn2/2.0.5 nghttp2/1.35.1
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 HTTPS-proxy MultiSSL Metalink

$ syft version
Application:   syft
Version:       0.34.0
BuildDate:     2021-12-22T21:15:39Z
GitCommit:     7f8cb0bd8068709982ef23e931e1ceaa2dfac955
GitTreeState:  clean
Platform:      windows/amd64
GoVersion:     go1.16.12
Compiler:      gc

any workaround to fix the issue?

**Comment by spiffcs** [comment]
Sorry Plaxo for the inconvenience - We'll be releasing an updated version shortly with some bug fixes that have windows checksums available. A small omission in our release file meant that it was not being propagated on release.

**Comment by luhring** [comment]
Is there a chance that this has been resolved? I see that a new version of Grype was released on Jan 11

**Comment by spiffcs** [comment]
@luhring next release this will be solved. The checksum updates did not go into the latest release.

**Comment by luhring** [comment]
(closing since the fix has been released)
