### ISSUE TITLE
add insecure flag to bypass ssl issues

### ISSUE THREAD

**Issue by fmtbkgiddiqq** [anchore/grype#582]
**What would you like to be added**:

An insecure flag that adds InsecureSkipVerify, etc. to HTTP calls on a one-off basis to allow for testing in internal infrastructure that may not use a public CA.

**Why is this needed**:

To use the tool in infrastructure / repo that are hosted using internal cert chain, i.e. not signed by public CA

**Additional context**:

**Comment by kzantow** [comment]
@fmtbkgiddiqq you can already do this with Yaml configuration or the `GRYPE_REGISTRY_INSECURE_SKIP_TLS_VERIFY=true` environment variable

**Comment by fmtbkgiddiqq** [comment]
This is really useful. Thanks.
