### ISSUE TITLE
Add support for cyclonedx 1.4 and VEX 

### ISSUE THREAD

**Issue by samj1912** [anchore/grype#591]
**What would you like to be added**: CycloneDX 1.4 was released with added support for a common vulnerability exchange format. 

It would be great if grype could output its vulnerability reports in this format. This could also be helpful down the road as a standardized format to attach vulnerability data as intoto attestations. 

**Why is this needed**: This provides a well defined standard to output and parse vulnerability information. syft already supports Cyclonedx SBOMs and this could be a great counterpart for grype. 

**Additional context**:
 More details at 
https://cyclonedx.org/capabilities/vex/

https://github.com/CycloneDX/sbom-examples/blob/master/VEX/vex.json

**Comment by nwl** [comment]
Syft ticket here: https://github.com/anchore/syft/issues/744

**Comment by samj1912** [comment]
Now that syft support for cyclonedx 1.4 is out, I believe this is unblocked. I might be able to get around to a draft PR this week.

**Comment by luhring** [comment]
That would be amazing! I'm very excited about this one.

**Comment by hectorj2f** [comment]
@luhring Are there any plans to support CycloneDX 1.4 in the incoming releases ? Do you have an idea when that could happen ? Thanks :).

**Comment by luhring** [comment]
@hectorj2f Just released!
