### ISSUE TITLE
--only-fixed not working with -o json

### ISSUE THREAD

**Issue by joel-eames-armis** [anchore/grype#593]
**What happened**: discovered that --only-fixed isn't working when output is json

**What you expected to happen**: expected that the json output would only include "fixed" vulnerabilities

**How to reproduce it (as minimally and precisely as possible)**: grype --only-fixed <image> -o json

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`: 0.31.1
- OS (e.g: `cat /etc/os-release` or similar): macOS

**Comment by luhring** [comment]
Hi @joel-eames-armis, any chance you are able to provide example output from the command you're running? I just tried on my machine, and it seems like the feature is working correctly.

Just to clarify what to expect with `--only-fixed` and `-o json`, you should see that the `.matches` array property contains only matches where the vulnerabilities have been fixed, and all other matches that were found (i.e. that have not been fixed) have been moved into the sibling property `.ignoredMatches` array.

**Comment by joel-eames-armis** [comment]
I was not able to reproduce the issue. I think I may have been working too late :/

**Comment by luhring** [comment]
Glad to hear it's working!
