### ISSUE TITLE
add grype image to ArtifactHub

### ISSUE THREAD

**Issue by developer-guy** [anchore/grype#613]
**What would you like to be added**:

**Why is this needed**:

ArtifactHub has a new feature called Container images repositories.

I would like to add Grype container image to ArtifactHub

https://artifacthub.io/docs/topics/repositories/#container-images-repositories

**Additional context**:

cc: @dirien @dentrax

**Comment by wagoodman** [comment]
The artifact in ArtifactHub is currently a test image and needs to be replaced with an official image before this issue can be considered done.

**Comment by tgerla** [comment]
I believe this is complete--please re-open if I'm wrong!
