### ISSUE TITLE
False positive (critical) on GHSA-8v27-2fg9-7h62

### ISSUE THREAD

**Issue by AleX77NP** [anchore/grype#632]
**What happened**:
Grype false positive critical vulnerability on GHSA-8v27-2fg9-7h62, despite the fact that it has been Withdrawn.
https://github.com/advisories/GHSA-8v27-2fg9-7h62

**What you expected to happen**:
Grype should't have reported this as a critical vulnerability.

**Comment by AleX77NP** [comment]
This image was used for testing: https://hub.docker.com/r/amopdev/grype-test

**Comment by spiffcs** [comment]
Also confirmed using the image that resulted in the issue in the first place:
<img width="648" alt="Screen Shot 2022-04-04 at 9 47 04 AM" src="https://user-images.githubusercontent.com/32073428/161558061-1753283e-84ca-4c06-a87f-633f6d0ed8a6.png">
