### ISSUE TITLE
Syft spdx-json files with cataloger enabled results in `unable to identify format`

### ISSUE THREAD

**Issue by pjbgf** [anchore/grype#655]
**What happened**:

`grype` cannot process `spdx-json` files generated by `syft` when cataloger is enabled.

```sh
$ curl -sSfL https://github.com/fluxcd/flux2/releases/download/v0.27.3/flux_0.27.3_sbom.spdx.json | grype                   
1 error occurred:
        * failed to catalog: unable to decode sbom: unable to identify format
```

**What you expected to happen**:

`grype` should support this format which simply adds an extra element named files.
By removing it, `grype` is happy again:
```sh
$ curl -sSfL https://github.com/fluxcd/flux2/releases/download/v0.27.3/flux_0.27.3_sbom.spdx.json | jq 'del(.files)' | grype
```

**How to reproduce it (as minimally and precisely as possible)**:
```sh
$ wget https://github.com/fluxcd/source-controller/archive/refs/tags/v0.21.2.tar.gz
$ SYFT_FILE_METADATA_CATALOGER_ENABLED=true syft packages v0.21.2.tar.gz --output spdx-json | grype
```

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:
```
Application:          grype
Version:              0.33.1
Syft Version:         v0.39.3
BuildDate:            2022-02-27T00:01:17Z
GitCommit:            b0c8dc0e578d4b7c38a6bb4bdfbbda21a4640e53
GitDescription:       v0.33.1
Platform:             linux/amd64
GoVersion:            go1.17.7
Compiler:             gc
Supported DB Schema:  3
```
- Output of `syft version`:
```
syft version
Application:     syft
Version:         0.40.0
BuildDate:       2022-03-02T16:44:56Z
GitCommit:       1e75cb0418df15f8bc8193b1b8a3b3a8d81cb3b0
GitDescription:  v0.40.0
Platform:        linux/amd64
GoVersion:       go1.17.7
Compiler:        gc
```
- OS (e.g: `cat /etc/os-release` or similar):
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by luhring** [comment]
@pjbgf Thanks for reporting this!

@kzantow Can you take a look at this?

**Comment by kzantow** [comment]
Yep, thanks for reporting this and providing an example!

**Comment by kzantow** [comment]
Hi @pjbgf It appears the `SPDXID` values are invalid in the files section, such as: `"SPDXID": "50791f8ccfdc13e2",` the spec requires the ID is in the format `SPDXRef-<something>`, but it's missing the `SPDXRef-` prefix. Were these files generated by Syft or some other way?

**Comment by kzantow** [comment]
Ok, I've figured out the issue here. It looks like you're using the `sbom-action` [to download Syft](https://github.com/fluxcd/flux2/blob/809cb798283296bb8b64acc7913ad180aad15374/.github/workflows/release.yaml#L29-L30), but it always has a pinned version that hasn't been updated in a little while, and it must be older than the one that has the aforementioned fix. We need to figure out a way to ensure this is more up to date. We definitely have some upcoming work for this, but in the meantime I can go ahead and bump the Syft version so it should be fixed for you in subsequent builds.

**Comment by pjbgf** [comment]
I downloaded the latest version (v0.40.0) on my machine and had the same problem by running:
```
$ wget https://github.com/fluxcd/source-controller/archive/refs/tags/v0.21.2.tar.gz
$ SYFT_FILE_METADATA_CATALOGER_ENABLED=true syft packages v0.21.2.tar.gz --output spdx-json | grype
 ✔ Indexed /tmp/syft-archive-contents-174708597
 ✔ Cataloged packages      [218 packages]
 ✔ Cataloged file metadata
 ✔ Cataloged file digests
1 error occurred:
        * failed to catalog: unable to decode sbom: unable to identify format
```

But I agree with you, we need to update to the latest in our pipeline once this is fixed.

**Comment by kzantow** [comment]
Ok, thanks for that context, I wasn't sure where the SBOM was coming from; let me dig into this further.

**Comment by kzantow** [comment]
Ok, I tracked this one down to another export issue and will be fixed in https://github.com/anchore/syft/pull/863

**Comment by pjbgf** [comment]
That's awesome, thank you so much @kzantow for the quick turn around. :bow: 

Let us know when a new release is out so we can re-test, update our repositories and feedback accordingly.

**Comment by kzantow** [comment]
@pjbgf new release created and the sbom-action updated, so please give this another try

**Comment by pjbgf** [comment]
I have tested locally and I can confirm it now works as expected.

Thank you very much @kzantow. Will close this now.
