### ISSUE TITLE
Clair vs Grype

### ISSUE THREAD

**Issue by ssbano** [anchore/grype#700]
Hi,

I have noticed a different score and amount of cve entered between products is this normal?

https://youtu.be/mhzKCz__dS0

Best Regards,
Fabio Sbano

**Comment by spiffcs** [comment]
Hi @ssbano! 

Without specific cases comparing the two, or more data on what was scanned, I don't think an issue on the repository is appropriate at this time. We're happy to look and see if any criticals are being missed or give a closer look at "normal" for your specific use case. 

Closing this for now, but let me know if you have any questions.

**Comment by spiffcs** [comment]
@ssbano if you have a sample repository setup with the above dashboard I'm happy to take a look at the differences and report back to you on the nuances and differences we have

**Comment by ssbano** [comment]
@spiffcs ,

Thank you very much for your attention i will provide a url in demo.fsbano.io

Please give me a few days to organize the environment

I will put the source code in git and the access url for analysis

Best Regards,
Fabio Sbano

**Comment by ssbano** [comment]
@spiffcs ,

Follow the repository below
https://github.com/ssbano/anteather/

Best Regards,
Fabio Sbano

**Comment by ssbano** [comment]
@spiffcs ,

DEMO - LIVE - https://ssbano.github.io/anteather/

Best Regards,
Fabio Sbano
