### ISSUE TITLE
Mismatch between go template field name and json field

### ISSUE THREAD

**Issue by ik1zow** [anchore/grype#707]
**What happened**:

    When defining a template to print the component with vulnerability issue the field name is "
"{{ (index .Artifact.Locations 0).RealPath }}"
while on json file (producted with -o json) the field name is "path" (instead of RealPath)

**What you expected to happen**:

I expect that field name reported on json is same as the one to be defined on template to select that field.

**How to reproduce it (as minimally and precisely as possible)**:
grype <image> -o json > test.json
Check that Artifact.Location is an array of "records" with key-values. Check that there is a key named "path"
Write a template to print also the path:
Template using extracted json names (not working)
"Package","Version Installed","Vulnerability ID","Severity","Path"
{{- range .Matches}}
"{{.Artifact.Name}}","{{.Artifact.Version}}","{{.Vulnerability.ID}}","{{.Vulnerability.Severity}}","{{ (index .Artifact.Locations 0).**Path** }}"
{{- end}}

Working template:
"Package","Version Installed","Vulnerability ID","Severity","Path"
{{- range .Matches}}
"{{.Artifact.Name}}","{{.Artifact.Version}}","{{.Vulnerability.ID}}","{{.Vulnerability.Severity}}","{{ (index .Artifact.Locations 0).**RealPath** }}"
{{- end}}

**Anything else we need to know?**:
To discover "right" name I used "{{ (index .Artifact.Locations 0) }}" and seen that on the output the field name is "RealPath"

**Environment**:
- Output of `grype version`:
- Application:          grype
Version:              0.34.7
Syft Version:         v0.42.4
BuildDate:            2022-03-24T19:36:25Z
GitCommit:            44e676488efe4ab4fd63438bbce539777a2b8922
GitDescription:       v0.34.7
Platform:             linux/amd64
GoVersion:            go1.18
Compiler:             gc
Supported DB Schema:  3

- OS (e.g: `cat /etc/os-release` or similar):
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by spiffcs** [comment]
@ik1zow is it possible there is a bug in the template?
```
(index .Artifact.Locations 0) <--- 
```
The above looks incorrect if you're trying to access the array element at 0? Or are you trying to make a count of how many locations exist? Either way let me know and we can debug this for sure.

**Comment by tgerla** [comment]
I'll go ahead and close this old issue but please feel free to re-open it or open a new one if it is still a problem!
