### ISSUE TITLE
Consistent sort order for grype output

### ISSUE THREAD

**Issue by exortech** [anchore/grype#709]
**What would you like to be added**:
It would be fantastic if the output produced by grype was consistently ordered. It does appear to be sorted by NAME, but a secondary sort by VULNERABILITY would ensure that the output is rendered consistently across runs.

**Why is this needed**:
We commit the output of our grype runs to version control after updating dependencies. The inconsistent sorting creates unnecessarily complex diffs.

**Comment by freedom-isnotanarchy** [comment]
I agree with the value of this enhancement. The proposed "consistently  rendered output", any consistent sort whatsoever, makes diffs possible.

**Comment by adriens** [comment]
Also, is sorted from `Critical`-> Negligible` it would make `| head`` much more interesting as people usually are looking for the worst one.

So finally it leads to make `grype` more efficient for end user :muscle: :pray:

**Comment by spiffcs** [comment]
Thanks for the issue @exortech! This looks like a pretty good option for a community PR or first issue if anyone on this thread wants to take a stab. If not I'll try and get around to this as soon as I have some time.

**Comment by maqzee-git** [comment]
➕ 1️⃣ for this one

**Comment by spiffcs** [comment]
I've added a PR to this issue for the table sort - if that's what we're looking for I'll go ahead and get one added for machine readable formats
