### ISSUE TITLE
:grey_question: Call grype from container to scan (podman) host containers :grey_question: 

### ISSUE THREAD

**Issue by adriens** [anchore/grype#732]
# :point_right: Context

This afternoon I did a short `grype` demo to a sysadmin. We are currently running containers thanks to `pdoman`. He was very positively impressed bu the tool.
Then he asked

> How can I install the tool ?

So I answered : 

> Just `brew install`gryp

But he wanted to run `grype` from its docker distribution, from `podman`.

 
- So he called it from the interactive to scan an image from `docker.io` :arrow_right: :+1: 
- .. Then from within the `podman` instance he tried to scan a container running on the host with podman :arrow_right: :-1: 

That was pretty logic, still we wondered if... (see following question) :point_down: 

# :grey_question: Question :magic_wand: 

:point_right:  How could we scan local running containers on `podman` from withi a containerized instance of `grype` ?

That could be an interesting trick to comfortably scan live podmans instances from an always up-to-date `grype` servce-like.

# :pray: Thank you

Thank you in advance for any help or feedback you'll be able to provide us.

**Comment by AErmie** [comment]
I was able to successfully run grype from a docker container, against another (locally built) docker container, using the following: 

```yaml
docker run --rm \
--volume /var/run/docker.sock:/var/run/docker.sock \
--name Grype anchore/grype:latest \
$(ContainerImageName):$(ContainerImageVersion)
```

**Comment by adriens** [comment]
Thanks a lot for the great cde snipper...and sorry for my late answer.
Hopefull the PR will be merged https://github.com/anchore/grype/pull/769

**Comment by joshbressers** [comment]
This can be done for podman, but it's a little more work

First run
```
podman system service --time=0 unix:///tmp/podman.sock
```
You can put the socket wherever you like.

Then you can run

```
podman run --rm -it -v /tmp/podman.sock:/var/run/docker.sock --name Grype docker.io/anchore/grype:latest docker:anchore/grype:latest
```

**Comment by adriens** [comment]
using `/tmp/podman.sock` makes it possible to stay rootless 👍 

Thanks for the tip 👍  @joshbressers
