### ISSUE TITLE
Request vulnerability data by a single cpe string

### ISSUE THREAD

**Issue by BrianPfitz** [anchore/grype#757]
**What would you like to be added**:
Hey guys, first of all thanks for this great tool! I really like working with Syft and Grype.
However, I would find it very practical to be able to query the Grype database with individual cpes (or with a list of several cpes). This is currently not possible, is it? Is there a possible workaround for this?

**Why is this needed**:
After an initial scan, I would also like to check the version of a cpe in which the vulnerability found (according to Grype) was fixed. This would be possible without any problems with the above-mentioned feature. In addition, the extensive Grype database could be used much more extensively.

**Comment by spiffcs** [comment]
Thanks @BrianPfitz for the enhancement suggestion! Just to get clarity here - you want something like `grype xxx <CPE1> <CPE2>` to get full details from the DB about what was found?

Current workaround would be to do something like getting the DB from sqlite and querying via the cli or a DB program like `DB Browser Sqlite`:
<img width="1792" alt="Screen Shot 2022-05-25 at 3 15 16 PM" src="https://user-images.githubusercontent.com/32073428/170350314-d9767e29-1a54-4e8e-80ce-c77bb368afb6.png">

**Comment by BrianPfitz** [comment]
Hey @spiffcs, thanks for your answer!
Yes, exactly! Just as you can run ```grype sbom:path/to/syft.json```, it would be nice if you could also run 
```grype cpe:path/to/cpe_list.csv```. 
In principle, the query for vulnerabilities should be based on the CPEs and less on the countless other pieces of information contained in an SBOM, right? If so, this "feature" could be implemented relatively straightforwardly.

**Comment by spiffcs** [comment]
Awesome! I'll talk with the team here and we can prioritize getting a look at adding this. Feel free to take a stab at writing a small PR to if you think it's straightforward =)

**Comment by BrianPfitz** [comment]
Hello @spiffcs,
Were you able to discuss my proposal in your meeting? What are your opinions on this?

In the meantime, I have looked over the code from time to time and have to conclude that it is unfortunately not as simple as I first thought. This is because everything is closely linked to Syft and the creation of an SBoM. Unfortunately, you can hardly reuse a function only with a CPE (and without locations, for example). 
I think I will search the database for the CPEs for now.

**Comment by spiffcs** [comment]
Thanks @BrianPfitz we've run into the same challenges you mentioned, but I have not had time to dig as deep as possible to come up with a solution I'm totally happy with for this one. Currently, I've also been browsing the DB to search for a highlighted match, but do admit it would be nice to have some CLI access in this manner.

When things start moving more on this issue and we have a solution we're happy with I'll update you. 

Thanks again for taking the time to look at the code to see if a PR from your end was possible!
