### ISSUE TITLE
Different reported CVEs between container image and filesystem methods for the same source code

### ISSUE THREAD

**Issue by andmagom** [anchore/grype#772]
**What happened**: 
Grype generates a different report for filesystem scanning and container image scanning for the same source code 

**What you expected to happen**: Grype generates the same report for filesystem scanning and container image scanning for the same code

**How to reproduce it**:
### Filesystem method
1. Download the [ v4.4.0 vscode server version](https://github.com/coder/code-server/releases/tag/v4.4.0) to your machine 
2. uncompress the file: `tar -xvf code-server-4.4.0-linux-amd64.tar.gz`
3. Go to the folder: `cd code-server-4.4.0-linux-amd64`
4. Analyze the code: `grype dir:.`
5. CVEs reported: Around **16 vulnerabilities**
![imagen](https://user-images.githubusercontent.com/13066717/172017936-df80e20b-63b3-4abc-885c-0e177d6a2dca.png)

### Container image method
1. Create a basic dockerfile inside code-server-4.4.0-linux-amd64 using alpine image to avoid adding new vulnerabilities related to the OS:

```
FROM alpine
COPY . .
```

2. Build the image: `docker build . -t vscode-server`
3. Analyze the image: `grype vscode-server`
4. CVEs reported: Around **662 vulnerabilities**
![imagen](https://user-images.githubusercontent.com/13066717/172017971-8282d638-1947-4f03-8cc6-f2533621b670.png)

 

**Anything else we need to know?**:
On the container image method, grype is reporting a lot of false positive vulnerabilities related to the vscode extensions folder

**Environment**:
- Output of `grype version`:
![imagen](https://user-images.githubusercontent.com/13066717/172017671-a7028a37-20a7-430b-b445-109dfcef3238.png)

- OS: macOs Big Sur v11.6

**Comment by andmagom** [comment]
Hi @luhring @spiffcs ! How are you two ? 
Did you two have a chance to review this ticket ? 
The amount of vulnerabilities is affecting the reputation for some docker images that include VScode server

**Comment by HellBoss69** [comment]
I have same issue identified on my side and here is a first analysis I did:

### Docker Image method

For npm, packages are identified and related vulnerabilities as well in any case (if package-lock.json is present or not) 

### Using Filesystem method

For npm, package are not identified if package-lock.json file is missing. In case package-lock.json is present, packages are identified and related vulnerabilities as well

What is done on the Docker Image method which make it work (without package-lock.json)  comparing to Filesystem method

**Comment by tgerla** [comment]
Hi @HellBoss69, sorry for the long delay replying to this issue. When you run a Syft scan on a directory versus an image, a different set of catalogers are run by default. Image scans are for detecting installations of things, and directory scans are for detecting declarations of things.

If you want closer behavior between the two different kinds of scans, you can manually enable the catalogers that you need. The list of default catalogers for images and directories are shown here: https://github.com/anchore/syft#image-scanning

You can use the --catalogers command line option to Syft to specify a list of catalogers to use. You will need to specify all of the catalogers you want to run for a particular scan. Hope this helps and let us know if you need anything else.
