### ISSUE TITLE
GHSA-x24g-9w7v-vprh included in grype 0.38.0

### ISSUE THREAD

**Issue by willyw0nka** [anchore/grype#779]
**What happened**: Scanning a docker image that contains only grype reports a critical vulnerability (GHSA-x24g-9w7v-vprh)

**What you expected to happen**: Scanning a docker image that contains only grype reports no vulnerabilities

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a docker image from the following Dockerfile
```Dockerfile
FROM debian
RUN apt update && apt upgrade -y
RUN apt install -y curl
RUN curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
RUN apt purge -y curl
```
2. Scan the docker image using `syft docker:<image_name> -o json | grype --only-fixed --add-cpes-if-none`.

**Anything else we need to know?**:
Scan output is the following:
```
NAME                                  INSTALLED                           FIXED-IN  TYPE       VULNERABILITY        SEVERITY
github.com/containerd/containerd      v1.5.10                             1.5.13    go-module  GHSA-5ffw-gxpp-mxpf  Medium
github.com/hashicorp/go-getter        v1.5.11                             1.6.1     go-module  GHSA-cjr4-fv6c-f3mv  High
github.com/hashicorp/go-getter        v1.5.11                             1.6.1     go-module  GHSA-fcgg-rvwg-jv58  High
github.com/hashicorp/go-getter        v1.5.11                             1.6.1     go-module  GHSA-x24g-9w7v-vprh  Critical
github.com/hashicorp/go-getter        v1.5.11                             1.6.1     go-module  GHSA-28r2-q6m8-9hpx  High
github.com/theupdateframework/go-tuf  v0.0.0-20220211205608-f0c3294f63b9  0.3.0     go-module  GHSA-66x3-6cw3-v5gj  High
```

**Environment**:
- Output of `grype version`: syft v0.46.2 + grype 0.38.0
- OS: Ubuntu 20.04.4 LTS

**Comment by willyw0nka** [comment]
This issue is fixed on commit 07dfb2871830a60219a072e348eed6567be9a2b4 but not pushed into a release. Is there a planned date for the next release?

**Comment by westonsteimel** [comment]
Thanks @willyw0nka , we are hoping to get releases out later today.  Also, regarding the version bumps of github.com/containerd/containerd and github.com/theupdateframework/go-tuf to address the others, we are aware and working on those, but the go-tuf one requires updating cosign and there are several breaking changes there that we need to address and the containerd one has some breakages within stereoscope that we'll need to address

**Comment by westonsteimel** [comment]
Sorry we weren't able to get releases out yesterday; hopefully we can cut them today.  Good news is we did get https://github.com/anchore/syft/commit/b8d1a46e7e5f39be39a2f4b7b5d803c95c6723ab in to address GHSA-66x3-6cw3-v5gj within syft, so once the syft release is cut we'll get that one updated in grype as well.

**Comment by westonsteimel** [comment]
[v0.39.0](https://github.com/anchore/grype/releases/tag/v0.39.0) of grype has just been released and should take care of all except for GHSA-5ffw-gxpp-mxpf.  We're still working through resolving some dependency conflicts on that one

**Comment by willyw0nka** [comment]
Thank you for your efforts!
