### ISSUE TITLE
feat: use ghsa to improve matching for cpes

### ISSUE THREAD

**Issue by cpendery** [anchore/grype#811]
Another thing which might potentially be useful (and should probably be configurable on individual ecosystem matcher level) could be if we find an NVD match and that CVE has a GHSA for another ecosystem (and the eocsystem we're matching for is supported by GitHub) we filter it out.  Hopefully that makes sense but if not I can try and explain it better.

_Originally posted by @westonsteimel in https://github.com/anchore/grype/issues/390#issuecomment-1052132016_

**Comment by cpendery** [comment]
I wanted to keep track of this idea when my pr closes its source issue in order to investigate in the future

**Comment by westonsteimel** [comment]
Yes, so I'm already working on a feature for this internally.  It will be configurable to define some hierarchy of namespaces which should be considered authoritative.  I'll let you know when I'm ready with it and you can try it out.
