### ISSUE TITLE
Add support for Swift/Cocoapods, Kotlin, and Rust

### ISSUE THREAD

**Issue by freedom-isnotanarchy** [anchore/grype#815]
**What would you like to be added**: 
- Add support for Swift/Cocoapods, Kotlin, and Rust.
- tidelift.com supports these.

**Why is this needed**:
- tidelift.com supports these.

**Additional context**:

Kotlin (Android) :  <-- (What does it use ?)
Rust (Cargo)  :  <---  TideLift 2022-q3
Swift (Cocoapods)  :  <--- TideLift  2022-q3
---------------------------
C# (Nuget)  :  TideLift  2022-q3
C# Dotnet (deps.json)  :  **Grype** 2022-q3
Golang (Go)  :  TideLift  2022-q3
Golang (go.mod)  :  **Grype** 2022-q3
Java (JAR, WAR, EAR, JPI, HPI)  :  **Grype** 2022-q3
Java (Maven)  :  TideLift  2022-q3
JavaScript (NPM, Yarn)  :  **Grype** 2022-q3
JavaScript (npm)  :  TideLift  2022-q3
PHP (Composer)  :  **Grype** 2022-q3
PHP (Packagist)  :  TideLift  2022-q3
Python (Egg, Wheel, Poetry, requirements.txt/setup.py files)  :  **Grype** 2022-q3
Python (PyPI, conda)  :  TideLift  2022-q3
Ruby (Gems)  :  **Grype** 2022-q3
Ruby (Rubygems)  :  TideLift  2022-q3

**LINKS**: 

- grype feature parity with osv.dev #794 : [https://github.com/anchore/grype/issues/794](url)
- docs: update to include rust #814 : [https://github.com/anchore/grype/pull/814/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5](url)

**Comment by spiffcs** [comment]
Thanks for the issue @freedom-isnotanarchy! I'll go through our issues and see if we have individual issues already filed for these 3 requests. Also did you mean to include more detailed links in the description that shows the support? Would you mind if I removed the excessive duplicated `support.tidelift.com` links from the issue?

**Comment by freedom-isnotanarchy** [comment]
> excessive duplicated `support.tidelift.com` links

Feel free, to remove.
I'm just including, to show Parity with Grype.  As well as any Gap that Grype has with TideLift. (It was a copy/paste)

**Comment by cpendery** [comment]
Happy to take on adding support in Syft and Grype for Swift/CocoaPods once I finish up Hex support

**Comment by tgerla** [comment]
Hello all, I believe that all three of the requested platforms are supported in some fashion here, on the Syft side:

Cocoapods: https://github.com/anchore/syft/pull/1081
Gradle/Kotlin: https://github.com/anchore/syft/pull/1719
Rust/Cargo: https://github.com/anchore/syft/pull/345

I'll go ahead and close this issue. If I am misunderstanding the requests here, or if we are missing any functionality for the above, please open a new issue with specific details. Thank you!
