### ISSUE TITLE
"Phantom" release 0.44.0

### ISSUE THREAD

**Issue by log2** [anchore/grype#842]
**What happened**:
Release 0.44.0 is shown as existent in git tags, so for example, using [asdf grype plugin](https://github.com/poikilotherm/asdf-grype):

`asdf latest grype` or `asdf latest grype 0.44.0`

which use git tags (see [this code](https://github.com/poikilotherm/asdf-grype/blob/main/lib/utils.bash#L27)), Show the following output:

`0.44.0`

However, that release cannot really be installed since it lacks actual binaries to download, so the following command fails:

`asdf install grype 0.44.0`

```
* Downloading grype release 0.44.0...
curl: (22) The requested URL returned error: 404
asdf-grype: Could not download https://github.com/anchore/grype/releases/download/v0.44.0/grype_0.44.0_darwin_amd64.tar.gz
```

**What you expected to happen**:

A release declared in tags should be downloadable and installable (either via asdf grype plugin, or by other means).

**How to reproduce it (as minimally and precisely as possible)**:

Just use asdf grype plugin with the aforementioned steps.

**Anything else we need to know?**:

Another way to fix this would be, in asdf grype plugin, to use a `curl https://api.github.com/repos/anchore/grype/releases` rather than a `git ls-tags` command, since the former looks at actual releases, while the latter lists barely the git tags (which may or may not have actual releases beneath them). In fact, the first command currently does not show `0.44.0` phantom version, while the second one does.

If release-less tags are actually possibile in grype repo, I'd be happy to contribute a change on grype plugin, in order to make detection algorithm more robust with respect to these issues.

**Environment**:
- Output of `grype version`: N/A
- OS (e.g: `cat /etc/os-release` or similar):

```
❯ sw_vers
ProductName:	macOS
ProductVersion:	12.5
BuildVersion:	21G72
```

**Comment by spiffcs** [comment]
Thanks for the issue @log2! It looks like a crucial step failed in our release workflow and I missed the report.

I've rebuilt the job so v0.44.0 should be coming out shortly. Closing this issue for now, but if we don't have a new v0.44.0 by this afternoon I'll check back in. Thanks again for the heads up.

**Comment by log2** [comment]
Release v0.44.0 is now online as you expected, @spiffcs . Thank you!
