### ISSUE TITLE
grype db update error

### ISSUE THREAD

**Issue by RunFox** [anchore/grype#846]
Hello. Sometimes command: _grype db update_ return such error:
"unable to update vulnerability database: unable to update vulnerability database: unable to download db: stream error: stream ID 1; INTERNAL_ERROR; received from peer"
What reason for it? What I can do to avoid such errors?

**Comment by tgerla** [comment]
Hi @RunFox, can you confirm that this error is intermittent? It could be an intermittent network connectivity error. Could you could provide the results of "grype db update -vv" during a failed update? That information would be helpful. Thank you!

**Comment by kzantow** [comment]
Since there hasn't been a response in quite some time, I'm going to close this issue -- if it continues to be a problem, please reopen it!

**Comment by sparrowt** [comment]
FWIW we saw this today 2024-02-27T16:02:37.959Z and are also assuming it's an intermittent network issue, though the error is somewhat obscure...!
