### ISSUE TITLE
Grype update command

### ISSUE THREAD

**Issue by willyw0nka** [anchore/grype#848]
**What would you like to be added**:
A new command ```grype update```
**Why is this needed**:
It would make the update process a lot easier. Grype already knows if you are running an outdated version.
**Additional context**:
Example output
```bash
$ grype <image_name>
New version of grype is available: 0.44.0 (currently running: 0.41.0)
You can update grype to the latest version running 'grype update'x
...
$ grype update
Updating grype...
$ grype version
Application:          grype
Version:              0.44.0
Syft Version:         v0.52.0
BuildDate:            2022-07-25T16:28:13Z
GitCommit:            a6ec8f11be5fdc116dc7bbfebdc03bfc13cd2005
GitDescription:       v0.44.0
Platform:             linux/amd64
GoVersion:            go1.18.4
Compiler:             gc
Supported DB Schema:  4
```

**Comment by spiffcs** [comment]
👋 Awesome! Thanks, @willyw0nka. This sounds like a great command to add and is a good first issue. Feel free to tackle it if you want to try and add a command to the project otherwise we'll try and find time to get it out into the next release.

**Comment by adriens** [comment]
:heavy_plus_sign: :+1: :smile_cat:

**Comment by willyw0nka** [comment]
Thanks! I'll give it a try myself when I find some time, probably after my vacations

**Comment by wagoodman** [comment]
I see there is a closed PR with this issue. It seems like one of the leading reasons for closing is that it duplicates logic about releasing to multiple places. I do generally agree with this point -- I think I'm in favor of closing this issue if we do not ever intend on adding this kind of functionality. We can always revisit this in the future.
