### ISSUE TITLE
Grype slow on parallel execution

### ISSUE THREAD

**Issue by cpendery** [anchore/grype#855]
**What happened**:
When I run Grype in parallel on a database, I'm seeing that up to 50% of the runtime is spending waiting on locks via pprof. I don't think it should be spending this long querying especially when the cli can only perform read only actions.

**What you expected to happen**:
I'd expect almost no time spending locking and unlocking the database

**How to reproduce it (as minimally and precisely as possible)**:
Run grype in parallel while using pprof on the process

**Anything else we need to know?**:
I think this would be an easy fix. Maybe adding in a readonly flag to the config which is on by default that appends `?cache=shared&mode=ro&_journal_mode=WAL` to the Grype db file path in order to set it as shared, read only, and disable locking by using Write-Ahead Logging based on connection string options from https://github.com/mattn/go-sqlite3

**Environment**:
- Output of `grype version`: `0.44.0`
- OS (e.g: `cat /etc/os-release` or similar): MacOS

**Comment by spiffcs** [comment]
We just merged:
https://github.com/anchore/grype/pull/854

This adds `connStr += "&immutable=1"` to the conn string it `READONLY`

We can also add the improvement here before the next release so that reads are the most efficient they can be.

**Comment by cpendery** [comment]
Awesome! Thanks for the quick response @spiffcs and sorry I didn't see that earlier
