### ISSUE TITLE
0.45.0 release is not available on docker hub

### ISSUE THREAD

**Issue by nigelgbanks** [anchore/grype#867]
**What happened**:

The latest release is not available on DockerHub:

https://hub.docker.com/r/anchore/grype/tags

**Comment by spiffcs** [comment]
Thanks for the shoutout @nigelgbanks - let me kick off our images release pipeline and I'll cut a patch with the correct images

**Comment by spiffcs** [comment]
We've also just bumped Grype to consume the latest syft so expect a v0.46.0 shortly!

**Comment by spiffcs** [comment]
The newest version has been released with the latest Syft and with docker images available on github!

Thanks again for the report!
