### ISSUE TITLE
:grey_question: grype as a dockerized API to remotely ask image scans :nerd_face: 

### ISSUE THREAD

**Issue by adriens** [anchore/grype#876]
# :grey_question: Context

Actually the `cli` is very useful but for some scenarios, it would be interesting to : 

> be able to call a `grype` based API where an input image/tag could be given as input... and here we would get as ouput the `json` version of the analysis

There is actually an image but it does not seem to be designed this way : am I wrong ?

That would be useful to centralize a kind of docker analysis engine.

Thank you in advance for any feedback.

**Comment by B3ns44d** [comment]
@adriens Yes, I believe this will be really beneficial, and integrating `Grype` with `Harbor` as a client/server model will be incredibly simple. `Trivy` already did [this](https://aquasecurity.github.io/trivy/v0.17.0/modes/client-server/).

**Comment by adriens** [comment]
Thanks @B3ns44d  for pointing [`Trivy`](https://github.com/aquasecurity/trivy) as I had never heard about it :bulb:

**Comment by joshbressers** [comment]
I do not think we should do this

Adding a remote API would increase the grype attack surface dramatically. It also puts you on the path to having to start adding permissions, authentication, and identity support (any application that supports network connections eventually turns into an identity provider given enough time), which would distract from the main mission of Grype

I would prefer we keep grype doing one thing, and doing it well

If there is an appetite for a remote API, I think a new project that uses grype would make the most sense. That way Grype won't get in the way of building an IDP ;)

**Comment by kzantow** [comment]
As there hasn't been any response on this in quite some time and we do not think it is something Grype should support, I'm going to close this -- but definitely open to help another project use Grype to accomplish this!
