### ISSUE TITLE
Support scanning all local images

### ISSUE THREAD

**Issue by kzantow** [anchore/grype#909]
There is a desire to have Grype scan all local Docker images.

_Originally posted by @freedom-isnotanarchy in https://github.com/anchore/grype/issues/882#issuecomment-1226626793_

**Comment by DanFainshteinGC** [comment]
Highly support this, I'm currently running the following bash script to do this:
`docker images --format "{{.Repository}}:{{.ID}}" | grep "^[^1;]" | while read line ; do
PACKAGE=$(echo $line | cut -d ":" -f 1)
ID=$(echo $line | cut -d ":" -f 2)
echo ID: $ID PACKAGE: $PACKAGE
grype $ID -o template -t csv.tmpl --file grype/$PACKAGE.csv --add-cpes-if-none
done`

**Comment by tgerla** [comment]
Thank you for the example script! We'll go ahead and close this issue since we don't plan on implementing this as a core feature of Grype, but the example script above is how we would suggest solving this problem.
