### ISSUE TITLE
Enable the Scorecard Github Action and badge

### ISSUE THREAD

**Issue by joycebrum** [anchore/grype#926]
Hi I am Joyce and I'm working on behalf of Google and the [OpenSSF][ossf] to help essential open-source projects improve their supply-chain security. The OpenSSF is a non-profit foundation backed by the Linux Foundation, dedicated to improving the security of the open-source community. It counts GitHub as a founding [member][ossf-membership].

**What would you like to be added**:
I would like to suggest for you to use Scorecard Github Action to increase the security of your repository.

The [Scorecard][sc] system combines dozens of automated checks to let maintainers better understand their project's supply-chain security posture. It is developed by the OpenSSF, with [direct support from GitHub][sc-blog].

However, the OpenSSF has also developed the [Scorecard GitHub Action][sc-gha], which adds the results of its checks to the project's [security dashboard](https://github.com/anchore/grype/security), as well as suggestions on how to solve any issues (see examples on the "Additional context"). This Action has been adopted by 1600+ projects already.

Would you be interested in a PR which adds this Action? Optionally, it can also publish your results to the OpenSSF REST API, which allows a [badge][badge] with the project's score to be added to its README.

**Why is this needed**:

Considering the relevance grype has on ensuring the security of many projects, it's been included in the OpenSSF's list of the 100 most critical open-source projects. Thus, the Scorecard Github Action adoption in this project would help you on the identification and the solution of security risks of the repository, which would increase the security of the project and garantee that it is (mostly) safe from malicious sabotage.

**Additional context**:

![Code scanning dashboard with multiple alerts, including Code-Review and Token-Permissions][img-security]

![Detail of a Token-Permissions alert, indicating the specific file and remediation steps][img-detail]

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[ossf]: https://openssf.org/
[ossf-membership]: https://openssf.org/about/members/
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

**Comment by adriens** [comment]
:eyes: 

I had never heard about [scorecard](https://github.com/ossf/scorecard) :grey_exclamation: Tanks a lot for having made me discover it :heavy_heart_exclamation: :pray:

**Comment by kzantow** [comment]
This is a great idea, definitely something we can look to do 👍
