### ISSUE TITLE
Grype reading SPDX file with json output gets UnknownScheme error

### ISSUE THREAD

**Issue by danielsotopino** [anchore/grype#948]
**What happened**:

I tried to use grype with an spdx file with a json output.

Used this command:
```
grype sbom:_manifest/spdx_2.2/manifest.spdx.json --add-cpes-if-none -o json -v 
```

Returns this error:
```
grype sbom:_manifest/spdx_2.2/manifest.spdx.json --add-cpes-if-none -o json -v
[0000]  INFO grype version: 0.50.2
[0002]  WARN no vulnerability namespaces found for language=
[0002]  WARN unable to show catalog image finished event: unable to show vulnerability report: unsupported source: "UnknownScheme"
```

If i use another type of output it works.

**What you expected to happen**:
Get a proper json output

**How to reproduce it (as minimally and precisely as possible)**:
run this on an SPDX file (generated with microsoft's sbom tool)
```
grype sbom:_manifest/spdx_2.2/manifest.spdx.json --add-cpes-if-none -o json -v 
```

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:
Application:          grype
Version:              0.50.2
Syft Version:         v0.57.0
BuildDate:            2022-09-20T19:54:28Z
GitCommit:            f094b860b9b9ebcdf06d9b9c6f7d5c000fad395b
GitDescription:       v0.50.2
Platform:             darwin/amd64
GoVersion:            go1.18.6
Compiler:             gc
Supported DB Schema:  4
- OS (e.g: `cat /etc/os-release` or similar):
OSX Big Sur 11.5.2

**Comment by spiffcs** [comment]
Hey @danielsotopino! Where is that SBOM being generated? Do you have the input or a sample of it that we can use to reproduce this on our side? Currently, with SPDX SBOM produced by Syft we do not see this issue, but always happy to look at the other outputs to see why we might not be generating a report for your specific input.

**Comment by tgerla** [comment]
We'll go ahead and close this issue but please feel free to re-open if it is still affecting you.

**Comment by javierfreire** [comment]
I ran into the same problem. The cause is the value of `documentNamespace`. I am testing a document generated by Trivy and it fails. The `documentNamespace` value is `http://aquasecurity.github.io/trivy/container_image/bitnami/wordpress-c4ada25e-69fb-400c-8145-347f4419d2be`. If I change `/container_image/` by `/image/` it works.

**Comment by spiffcs** [comment]
👋  hey @javierfreire!

Let me get this replicated -  can you add the `Trivy` commands you're running here to generated the SBOM with that URL?

I can get grype updated to the correct SPDX libraries so that it validates that field as correct.

The SPDX documentation says the field should be compatible with [RFC-3986](https://tools.ietf.org/html/rfc3986). The above string definitely meets that specification so it's probably an issue where grype has an older version of the SPDX specification validation.

**Comment by javierfreire** [comment]
Hello, @spiffcs! Thanks for your attention.

With a simplified SPXD like this:

```
{
  "spdxVersion": "SPDX-2.3",
  "dataLicense": "CC0-1.0",
  "SPDXID": "SPDXRef-DOCUMENT",
  "name": "bitnami/wordpress",
  "documentNamespace": "http://aquasecurity.github.io/trivy/container_image/bitnami/wordpress-a00a8026-16fd-431e-94c8-3f02250f61a4",
  "creationInfo": {
    "licenseListVersion": "",
    "creators": [
      "Organization: aquasecurity",
      "Tool: trivy-0.41.0"
    ],
    "created": "2023-05-11T09:58:14Z"
  },
  "packages": [
    {
      "name": "acl",
      "SPDXID": "SPDXRef-Package-d9f82fb26464b3f0",
      "versionInfo": "2.2.53-10",
      "supplier": "Organization: Guillem Jover \u003cguillem@debian.org\u003e",
      "downloadLocation": "NONE",
      "sourceInfo": "built package from: acl 2.2.53-10",
      "licenseConcluded": "GPL-2.0-only AND LGPL-2.0-only AND LGPL-2.1-only",
      "licenseDeclared": "GPL-2.0-only AND LGPL-2.0-only AND LGPL-2.1-only",
      "copyrightText": "",
      "externalRefs": [
        {
          "referenceCategory": "PACKAGE-MANAGER",
          "referenceType": "purl",
          "referenceLocator": "pkg:deb/debian/acl@2.2.53-10?arch=amd64\u0026distro=debian-11.7"
        }
      ],
      "attributionTexts": [
        "PkgID: acl@2.2.53-10",
        "LayerDigest: sha256:c3015ae15f8082526120dbfffceb8e32f74d62a3da3f5a389ea9315b2eaf67fd",
        "LayerDiffID: sha256:281d24b10b030ade178a187d9e20b6bfb26096a7e4b4765acbc2f90b9b9633a1"
      ],
      "primaryPackagePurpose": "LIBRARY"
    }
  ],
  "relationships": [
  ]
}
```

When I execute `grype spdx.json  --output json`, the output is:

```
 ✔ Vulnerability DB        [no update available]
 ✔ Scanning image...       [0 vulnerabilities]
   ├── 0 critical, 0 high, 0 medium, 0 low, 0 negligible
   └── 0 fixed
[0001] ERROR unable to show grype-vulnerability-scanning-finished event: unable to show vulnerability report: unsupported source: "UnknownScheme"
```

If I change the `documentNamespace` to `http://aquasecurity.github.io/trivy/container_image/bitnami/image/wordpress-a00a8026-16fd-431e-94c8-3f02250f61a4` (I added `/image`) it works.

**Comment by spiffcs** [comment]
Ran the above simplified SPDX against the latest grype this morning to investigate further and it looks like we picked up the correct upstream library changes that now support decoding this portion of the document:
```
➜  grype git:(1306-failure-to-validate) ✗ grype version
Application:          grype
Version:              0.64.2
Syft Version:         v0.85.0
BuildDate:            2023-07-19T20:36:20Z
GitCommit:            brew
GitDescription:       [not provided]
Platform:             darwin/amd64
GoVersion:            go1.20.6
Compiler:             gc
Supported DB Schema:  5
```

I can confirm that `documentNamespace` URL are supported where an `_` case exists.

Closing this now, but if you see further issues for more complex cases @javierfreire feel free to shout out and I'll take a look at those too!
