### ISSUE TITLE
Unicode in output of Grype 0.59.0

### ISSUE THREAD

**Issue by Moses2k** [anchore/grype#959]
**What happened**: Running Grype on an Ubuntu container image and get unicode for symbols (&, $, etc..) in the purl string
command:  `grype ubuntu -o embedded-cyclonedx-vex-json`
**What you expected to happen**: Should include the symbols rather than the unicdoe

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: Example below from
"purl": "pkg:deb/debian/zlib1g@1:1.2.8.dfsg-5?arch=amd64\u0026upstream=zlib\_u0026_distro=debian-9",

**Environment**:
- Output of `grype version`:  "purl": "pkg:deb/debian/zlib1g@1:1.2.8.dfsg-5?arch=amd64\u0026upstream=zlib\_u0026_distro=debian-9",
- OS (e.g: `cat /etc/os-release` or similar): MacOS Monterrey 12.6

**Comment by Moses2k** [comment]
Thanks @kzantow  for the prompt response.  It's not just in the purl btw,  have seen it in other data elements as well.

**Comment by kzantow** [comment]
@Moses2k do you have an example of some other fields (it might make things easier to track down)?

**Comment by Moses2k** [comment]
See it in the affects section of the vulns and also the bom-ref and publisher fields. 
  
     "affects": [
        {
          "ref": "pkg:deb/ubuntu/passwd@1:4.8.1-2ubuntu2?arch=arm64\u0026upstream=shadow\u0026distro=ubuntu-22.04\u0026package-id=ede75cd51b5b18d7"
        }
      ],


"bom-ref": "pkg:deb/ubuntu/adduser@3.118ubuntu5?arch=all\u0026distro=ubuntu-22.04\u0026package-id=78ce150ba8cd5542",
      "type": "library",
      "publisher": "Ubuntu Developers \u003cubuntu-devel-discuss@lists.ubuntu.com\u003e",
      "name": "adduser",
      "version": "3.118ubuntu5",
      "licenses": [

**Comment by kzantow** [comment]
Ah, thanks @Moses2k; it still looks like PURLs -- good info 👍

**Comment by kzantow** [comment]
FYI -- I've opened a PR against the `cyclonedx-go` library for this: https://github.com/CycloneDX/cyclonedx-go/pull/72

**Comment by Moses2k** [comment]
It is a cosmetic issue but also we do pipe in CycloneDX into a graph data model and so string searches for these attributes also become impacted.  Thanks.
