### ISSUE TITLE
Configuration search path logic mismatches on `./config.yaml`

### ISSUE THREAD

**Issue by victor-li** [anchore/grype#960]
As defined in the https://github.com/anchore/grype/blob/main/README.md#configuration section, Grype should have the following configuration search paths:

- `.grype.yaml`
- `.grype/config.yaml`
- `~/.grype.yaml`
- `<XDG_CONFIG_HOME>/grype/config.yaml`

and should not match on `./config.yaml`.

On this line: https://github.com/anchore/grype/blob/4cda526992d5003dcbab68c9a7479a653dfde008/internal/config/application.go#L212 the current directory is added to Viper's config paths, but is not removed from the config paths to check step 2.

**Comment by kzantow** [comment]
Hi @victor-li very nice find! It looks like we may not be _replacing_ the path the right way, but instead [appending to it](https://github.com/anchore/grype/blob/4cda526992d5003dcbab68c9a7479a653dfde008/internal/config/application.go#L221). We'll add this to the backlog.

**Comment by kzantow** [comment]
This was fixed as part of the CLIO port: https://github.com/anchore/grype/pull/1437
