### ISSUE TITLE
Incorrect artifact entry in json report for grype v0.51.0

### ISSUE THREAD

**Issue by poum** [anchore/grype#967]
**What happened**:
got a json report with a list of vulnerabilities having each the same non corresponding artifact entry (the first purl one)
All other entries (vulnerabilitty, etc ...) in matches list appear to be correct.
The text report is correct

**What you expected to happen**:
getting a json report with a list of vulnerabilities having the corresponding artifact entry

**How to reproduce it (as minimally and precisely as possible)**:
grype -o json purl:purl.txt

with purl.txt:
pkg:maven/org.apache.ant/ant@1.10.8
pkg:maven/org.apache.logging.log4j/log4j-core@2.14.1

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:
Application:          grype
Version:              0.51.0
Syft Version:         v0.59.0
BuildDate:            2022-10-17T23:56:55Z
GitCommit:            4cda526992d5003dcbab68c9a7479a653dfde008
GitDescription:       v0.51.0
Platform:             linux/amd64
GoVersion:            go1.18.7
Compiler:             gc
Supported DB Schema:  5

- OS (e.g: `cat /etc/os-release` or similar):
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by kzantow** [comment]
Thanks @poum. I can confirm I can reproduce this with your instructions and note that the artifact is incorrect for the `log4j` vulnerabilities, instead it has `ant` for everything, very odd!

**Comment by poum** [comment]
indeed. with 3 or more you always will have ant instead of the correct artefact. Im not a go guru but something with a shared reference for artefact instead of an instance ?
-------- Message d'origine --------De : Keith Zantow ***@***.***> Date : 25/10/2022  17:41  (GMT+01:00) À : anchore/grype ***@***.***> Cc : poum ***@***.***>, Mention ***@***.***> Objet : Re: [anchore/grype] stuck artifact entry in json report for grype v0.51.0 (Issue #967) 
Thanks @poum. I can confirm I can reproduce this with your instructions and note that the artifact is incorrect for the log4j vulnerabilities, instead it has ant for everything, very odd!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/anchore/grype/issues/967#issuecomment-1290766265",
"url": "https://github.com/anchore/grype/issues/967#issuecomment-1290766265",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
