### ISSUE TITLE
Feature Request: Support for Custom / Internal Vulnerability Data Sources

### ISSUE THREAD

**Issue by menocu** [anchore/grype#971]
**What would you like to be added**:
Support for scanning against custom/internal sources of vulnerability data in addition to the standard grype vulnerability.db.

**Why is this needed**:
I have a number of internal projects that all depend on internal package x. When I fix a vulnerability in package x, I'd like to be able to register this vulnerability in an internal vulnerability database, and have regular ci/cd initiated grype runs against dependent projects begin alerting about this vulnerability.

**Additional context**:
I've messed around a little here, and I can get more-or-less the functionality I'm looking for by pointing the `update-url` setting to a custom listing file which in turn points to a custom database consisting of the most recent vulnerability.db with custom vulnerability data appended. While this works, it all feels a bit hacky, and it might be nice to instead support fetching and scanning against multiple listing.json and vulnerability.db files.  I'm happy to take this on if this sounds sane / useful.

**Comment by tgerla** [comment]
Hi @menocu, thank you for the suggestion. We're actually working through some steps that will allow us to open up the process by which the Grype database is generated, so you'll be able to add your own sources of data. Please stay tuned--we're not there yet but it's a high priority for us.

**Comment by tgerla** [comment]
Our Grype database pipeline has now been open-sourced! It's possible now to implement your own vulnerability sources. We're starting a blog series on implementing a new source: https://anchore.com/blog/build-your-own-custom-data-provider-for-grype-with-vunnel/

Hope this helps!
