### ISSUE TITLE
Incorrect python version comparisons for rc releases

### ISSUE THREAD

**Issue by westonsteimel** [anchore/grype#986]
**What happened**:

Grype reports that version 22.10.0 of the PyPI [twisted](https://pypi.org/project/Twisted/) module is < version 22.10.0rc1

```sh
grype file:requirements.txt
 ✔ Vulnerability DB        [no update available]
 ✔ Indexed requirements.txt
 ✔ Cataloged packages      [1 packages]
 ✔ Scanned image           [1 vulnerabilities]

NAME     INSTALLED  FIXED-IN    TYPE    VULNERABILITY        SEVERITY
twisted  22.10.0    22.10.0rc1  python  GHSA-vg46-2rrj-3647  Medium
```

**What you expected to happen**:

22.10.0 should be considered > 22.10.0rc1 for python

**How to reproduce it (as minimally and precisely as possible)**:

Using this [requirements.txt](https://github.com/anchore/grype/files/9955536/requirements.txt)

`grype file:requirements.txt`

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:
```sh
Application:          grype
Version:              0.52.0
Syft Version:         v0.60.3
BuildDate:            2022-11-03T17:15:32Z
GitCommit:            c8ddd7e218f63eb3adac1ec98ba9d8db9f3f3fec
GitDescription:       v0.52.0
Platform:             darwin/arm64
GoVersion:            go1.18.7
Compiler:             gc
Supported DB Schema:  5
```
- OS (e.g: `cat /etc/os-release` or similar): mac os

**Comment by westonsteimel** [comment]
We probably need a python version object at https://github.com/anchore/grype/tree/main/grype/version/.  As an example, the logic trivy uses for [PEP 440](https://peps.python.org/pep-0440/) version parsing is https://github.com/aquasecurity/go-pep440-version/blob/main/version.go

**Comment by willmurphyscode** [comment]
This seems to have been fixed by intermediate development; I'm not longer able to reproduce it with the steps provided. However, I'm still tying it to #1510 since the specific request here is to use PEP440 to compare python versions, which is implemented in that PR.
