### ISSUE TITLE
Add pre-packaged Grype image with the latest Grype DB

### ISSUE THREAD

**Issue by kzantow** [anchore/grype#987]
**What would you like to be added**:
Daily publishing of a container which includes both Grype and a pre-packaged DB.

This was a request which came up during the community meeting with a bit of context here: https://github.com/anchore/grype/issues/837#issuecomment-1205509596

**Why is this needed**:
In order to run Grype without the need to download a database.

**Comment by joshbressers** [comment]
Would we want to rebuild the container image daily to pick up the latest DB?

**Comment by kzantow** [comment]
@joshbressers yes, we'd need to rebuild the container _after_ the daily DB is built, I think.

**Comment by kzantow** [comment]
Closing as a duplicate of #837
