### ISSUE TITLE
CodeQL not working after permission restriction

### ISSUE THREAD

**Issue by joycebrum** [anchore/grype#991]
**What happened**:
The action got a permission denied during its execution

**What you expected to happen**:
Run with success

**How to reproduce it (as minimally and precisely as possible)**:
Any push on main branch should be failing

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by joycebrum** [comment]
Should I also close the issue or leave it open to be linked with https://github.com/anchore/grype/pull/990?

**Comment by kzantow** [comment]
@joycebrum let's leave it open 👍
